<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;




class BillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('bills')->insert(
            [
                ['id' => '1','bills_sale_day' => '2021-05-17 17:11:25','bill_pay_day' => '2021-05-21 11:06:25','bill_descriptions' => 'Nah','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '2','staff_set_bill_shipping' => '3','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '350000','bill_custormer_id' => '1','created_at' => NULL,'updated_at' => '2021-05-21 04:17:14'],
  ['id' => '2','bills_sale_day' => '2021-05-17 17:12:00','bill_pay_day' => '2021-05-21 11:13:32','bill_descriptions' => 'Ship ngay','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '3','staff_set_bill_shipping' => '6','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '350000','bill_custormer_id' => '2','created_at' => NULL,'updated_at' => '2021-05-23 07:54:36'],
  ['id' => '3','bills_sale_day' => '2021-05-17 18:20:07','bill_pay_day' => '2021-05-23 14:52:11','bill_descriptions' => 'Ship vào hôm thứ 3 tuần tới','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '5','staff_set_bill_shipping' => '5','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '260000','bill_custormer_id' => '3','created_at' => NULL,'updated_at' => '2021-05-23 07:54:20'],
  ['id' => '4','bills_sale_day' => '2021-05-17 18:27:38','bill_pay_day' => '2021-05-24 15:56:59','bill_descriptions' => 'Không có gì','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '3','staff_set_bill_ship' => '5','staff_set_bill_shipping' => '6','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '70000','bill_custormer_id' => '4','created_at' => NULL,'updated_at' => '2021-05-24 08:58:19'],
  ['id' => '5','bills_sale_day' => '2021-05-17 18:28:20','bill_pay_day' => NULL,'bill_descriptions' => 'Hay quá vậy ta','bill_state' => 'Hủy','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => '2','bill_staff_id' => NULL,'bill_total' => '70000','bill_custormer_id' => '5','created_at' => NULL,'updated_at' => '2021-05-27 09:00:04'],
  ['id' => '6','bills_sale_day' => '2021-05-17 20:38:18','bill_pay_day' => '2021-05-23 14:52:19','bill_descriptions' => 'Ship vào khu cách ly','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '3','staff_set_bill_shipping' => '5','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '385000','bill_custormer_id' => '6','created_at' => NULL,'updated_at' => '2021-05-23 07:54:19'],
  ['id' => '7','bills_sale_day' => '2021-05-23 14:43:57','bill_pay_day' => '2021-05-23 14:52:09','bill_descriptions' => 'Ship nhanh cho anh nhé','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '3','staff_set_bill_shipping' => '6','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '315000','bill_custormer_id' => '7','created_at' => NULL,'updated_at' => '2021-05-23 07:54:34'],
  ['id' => '8','bills_sale_day' => '2021-05-23 14:45:10','bill_pay_day' => '2021-05-27 15:58:54','bill_descriptions' => 'Ship nhanh cho anh nhé','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '2','staff_set_bill_shipping' => '2','staff_set_bill_done' => '2','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '315000','bill_custormer_id' => '8','created_at' => NULL,'updated_at' => '2021-05-30 05:08:28'],
  ['id' => '9','bills_sale_day' => '2021-05-23 14:49:04','bill_pay_day' => '2021-05-23 14:52:05','bill_descriptions' => 'Không','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '5','staff_set_bill_shipping' => '5','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '35000','bill_custormer_id' => '9','created_at' => NULL,'updated_at' => '2021-05-23 07:54:17'],
  ['id' => '10','bills_sale_day' => '2021-05-24 15:44:35','bill_pay_day' => '2021-05-24 15:56:55','bill_descriptions' => 'Không','bill_state' => 'Cần giao hàng','staff_set_bill_accepted' => '3','staff_set_bill_ship' => '2','staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '105000','bill_custormer_id' => '10','created_at' => NULL,'updated_at' => '2021-05-27 08:58:37'],
  ['id' => '11','bills_sale_day' => '2021-05-27 16:15:14','bill_pay_day' => '2021-05-27 17:16:30','bill_descriptions' => 'Không','bill_state' => 'Đang giao hàng','staff_set_bill_accepted' => '1','staff_set_bill_ship' => '2','staff_set_bill_shipping' => '2','staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '155000','bill_custormer_id' => '11','created_at' => NULL,'updated_at' => '2021-05-30 05:08:23'],
  ['id' => '12','bills_sale_day' => '2021-05-27 17:15:23','bill_pay_day' => '2021-05-30 12:08:12','bill_descriptions' => 'Không','bill_state' => 'Đã xác thực','staff_set_bill_accepted' => '2','staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '70000','bill_custormer_id' => '12','created_at' => NULL,'updated_at' => '2021-05-30 12:08:12'],
  ['id' => '13','bills_sale_day' => '2021-05-30 12:10:38','bill_pay_day' => '2021-05-30 12:10:52','bill_descriptions' => 'Ship nhanh cho mình nhé','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '2','staff_set_bill_shipping' => '2','staff_set_bill_done' => '2','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '682000','bill_custormer_id' => '13','created_at' => NULL,'updated_at' => '2021-05-30 05:11:07'],
  ['id' => '14','bills_sale_day' => '2021-05-30 16:44:19','bill_pay_day' => NULL,'bill_descriptions' => 'Cảm ơn em','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '105000','bill_custormer_id' => '15','created_at' => NULL,'updated_at' => NULL],
  ['id' => '15','bills_sale_day' => '2021-05-30 17:38:07','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '16','created_at' => NULL,'updated_at' => NULL],
  ['id' => '16','bills_sale_day' => '2021-05-30 17:38:43','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '17','created_at' => NULL,'updated_at' => NULL],
  ['id' => '17','bills_sale_day' => '2021-05-30 17:38:47','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '18','created_at' => NULL,'updated_at' => NULL],
  ['id' => '18','bills_sale_day' => '2021-05-30 17:38:51','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '19','created_at' => NULL,'updated_at' => NULL],
  ['id' => '19','bills_sale_day' => '2021-05-30 17:40:01','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '20','created_at' => NULL,'updated_at' => NULL],
  ['id' => '20','bills_sale_day' => '2021-05-30 17:40:39','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '21','created_at' => NULL,'updated_at' => NULL],
  ['id' => '21','bills_sale_day' => '2021-05-30 17:41:15','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '22','created_at' => NULL,'updated_at' => NULL],
  ['id' => '22','bills_sale_day' => '2021-05-30 17:41:44','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '23','created_at' => NULL,'updated_at' => NULL],
  ['id' => '23','bills_sale_day' => '2021-05-30 17:41:58','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '24','created_at' => NULL,'updated_at' => NULL],
  ['id' => '24','bills_sale_day' => '2021-05-30 17:42:16','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '25','created_at' => NULL,'updated_at' => NULL],
  ['id' => '25','bills_sale_day' => '2021-05-30 17:42:36','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '26','created_at' => NULL,'updated_at' => NULL],
  ['id' => '26','bills_sale_day' => '2021-05-30 17:43:24','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '27','created_at' => NULL,'updated_at' => NULL],
  ['id' => '27','bills_sale_day' => '2021-05-30 17:43:42','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '28','created_at' => NULL,'updated_at' => NULL],
  ['id' => '28','bills_sale_day' => '2021-05-30 17:45:21','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '105000','bill_custormer_id' => '29','created_at' => NULL,'updated_at' => NULL],
  ['id' => '29','bills_sale_day' => '2021-06-06 22:38:32','bill_pay_day' => '2021-06-08 16:43:40','bill_descriptions' => 'Giao hàng cho trận bóng ngày mai','bill_state' => 'Hủy','staff_set_bill_accepted' => '1','staff_set_bill_ship' => '1','staff_set_bill_shipping' => '1','staff_set_bill_done' => '1','staff_set_bill_cancel' => '1','bill_staff_id' => NULL,'bill_total' => '258000','bill_custormer_id' => '30','created_at' => NULL,'updated_at' => '2021-06-08 11:18:09'],
  ['id' => '30','bills_sale_day' => '2021-06-10 14:50:17','bill_pay_day' => '2021-06-10 14:52:10','bill_descriptions' => 'Không','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '1','staff_set_bill_ship' => '1','staff_set_bill_shipping' => '1','staff_set_bill_done' => '1','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '210000','bill_custormer_id' => '31','created_at' => NULL,'updated_at' => '2021-06-10 07:52:53'],
  ['id' => '31','bills_sale_day' => '2021-06-10 14:51:29','bill_pay_day' => '2021-06-10 14:52:16','bill_descriptions' => 'Không','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '1','staff_set_bill_ship' => '1','staff_set_bill_shipping' => '1','staff_set_bill_done' => '1','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '210000','bill_custormer_id' => '32','created_at' => NULL,'updated_at' => '2021-06-10 07:54:19'],
  ['id' => '32','bills_sale_day' => '2021-06-11 21:50:05','bill_pay_day' => '2021-06-14 18:19:34','bill_descriptions' => 'Không','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '1','staff_set_bill_ship' => '3','staff_set_bill_shipping' => '5','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '140000','bill_custormer_id' => '33','created_at' => NULL,'updated_at' => '2021-06-14 11:22:19'],
  ['id' => '33','bills_sale_day' => '2021-06-14 18:17:56','bill_pay_day' => '2021-06-14 18:19:38','bill_descriptions' => 'Không','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '1','staff_set_bill_ship' => '3','staff_set_bill_shipping' => '5','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '105000','bill_custormer_id' => '34','created_at' => NULL,'updated_at' => '2021-06-14 11:22:16']

            ]
        );
    }
}
