<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;



class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('products')->insert(
            [
        //        [
        //         //    'product_id' => 'product_001',
        //            'categories_id' => 7,
        //            'product_name'=> 'Cà Phê Sữa Đá',
        //            'product_slug'=>'',
        //            'product_description'=> 'Hương vị cà phê Việt Nam đích thực! Từng hạt cà phê hảo hạng được chọn bằng tay, phối trộn độc đáo giữa hạt Robusta từ cao nguyên Việt Nam, thêm Arabica thơm lừng. Cà phê được pha từ Phin truyền thống, hoà cùng sữa đặc sánh và thêm vào chút đá tạo nên ly Phin Sữa Đá – Đậm Đà Chất Phin.',
        //            'product_image'=>'uploads/image/products/ca-phe-sua-da.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_002',
        //            'categories_id' => 7,
        //            'product_name'=> 'Cà Phê Đen Đá',
        //            'product_slug'=>'',
        //            'product_description'=> 'Dành cho những tín đồ cà phê đích thực! Hương vị cà phê truyền thống được phối trộn độc đáo tại Highlands. Cà phê đậm đà pha hoàn toàn từ Phin, cho thêm 1 thìa đường, một ít đá viên mát lạnh, tạo nên Phin Đen Đá mang vị cà phê đậm đà chất Phin. ',
        //            'product_image'=>'uploads/image/products/ca-phe-den-da.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_003',
        //            'categories_id' => 7,
        //            'product_name'=> 'Cà Phê Đen Nóng',
        //            'product_slug'=>'',
        //            'product_description'=> 'Dành cho những tín đồ cà phê đích thực! Hương vị cà phê truyền thống được phối trộn độc đáo tại Highlands. Cà phê đậm đà pha từ Phin, cho thêm 1 thìa đường, mang đến vị cà phê đậm đà chất Phin. ',
        //            'product_image'=>'uploads/image/products/ca-phe-den-da.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_004',
        //            'categories_id' => 7,
        //            'product_name'=> 'Cà Phê Sữa Nóng',
        //            'product_slug'=>'',
        //            'product_description'=> 'Hương vị cà phê Việt Nam đích thực! Từng hạt cà phê hảo hạng được chọn bằng tay, phối trộn độc đáo giữa hạt Robusta từ cao nguyên Việt Nam, thêm Arabica thơm lừng. Kết hợp với nước sôi từng giọt cà phê được chiết xuất từ Phin truyền thống, hoà cùng sữa đặc sánh tạo nên ly Phin Sữa Nóng – Đậm đà chất Phin.',
        //            'product_image'=>'uploads/image/products/ca-phe-sua-da.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_005',
        //            'categories_id' => 6,
        //            'product_name'=> 'PhiDi Kem Sữa',
        //            'product_slug'=>'',
        //            'product_description'=> 'PhinDi Kem Sữa - Cà phê Phin thế hệ mới với chất Phin êm hơn, kết hợp cùng Kem Sữa béo ngậy mang đến hương vị mới lạ, không thể hấp dẫn hơn!',
        //            'product_image'=>'uploads/image/products/phi-di-kem-sua.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_006',
        //            'categories_id' => 6,
        //            'product_name'=> 'PhiDi Choco',
        //            'product_slug'=>'',
        //            'product_description'=> 'PhinDi Choco - Cà phê Phin thế hệ mới với chất Phin êm hơn, kết hợp cùng Choco ngọt tan mang đến hương vị mới lạ, không thể hấp dẫn hơn!',
        //            'product_image'=>'uploads/image/products/phi-di-cho-co.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_007',
        //            'categories_id' => 6,
        //            'product_name'=> 'Cà Phê Sữa Chua',
        //            'product_slug'=>'',
        //            'product_description'=> 'Nhâm nhi một tách cà phê mỗi ngày là cách tiếp thêm năng lượng tích cực của nhiều thế hệ người Việt Nam. Để hương vị cà phê truyền thống không nhàm chán, bạn có thể học cách pha cafe sữa chua của chúng tôi. Đây là sự kết hợp hoàn hảo, mang đến hương vị thanh mát mới lạ, lại có lợi cho sức khỏe, hệ tiêu hóa của bạn đấy! ',
        //            'product_image'=>'uploads/image/products/bac-xiu.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_008',
        //            'categories_id' => 6,
        //            'product_name'=> 'Cà Phê Trứng',
        //            'product_slug'=>'',
        //            'product_description'=> 'Nếu là người Hà thành hay là những người sành và yêu thích cafe thì chắc hẳn bạn không còn xa lạ gì với món cafe trứng nữa rồi. Được chế biến và khởi nguồn đầu tiên từ Hà Nội, đến nay cafe trứng dường như còn nổi danh trên khắp thế giới thu hút rất nhiều du khách đến thưởng thức.',
        //            'product_image'=>'uploads/image/products/ca-phe-sua-da.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_009',
        //            'categories_id' => 6,
        //            'product_name'=> 'Bạc Xỉu',
        //            'product_slug'=>'',
        //            'product_description'=> 'Nếu Phin Sữa Đá dành cho các bạn đam mê vị đậm đà, thì Bạc Xỉu Đá là một sự lựa chọn nhẹ “đô" cà phê nhưng vẫn thơm ngon, chất lừ không kém!',
        //            'product_image'=>'uploads/image/products/bac-xiu.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_010',
        //            'categories_id' => 6,
        //            'product_name'=> 'Cà Phê Cốt Dừa',
        //            'product_slug'=>'',
        //            'product_description'=> 'Bạn có phải là fan của món cafe cốt dừa vô cùng nổi tiếng của Cộng cà phê? Với những ai yêu cà phê và thích thú với hương vị béo ngậy của dừa hòa quyện với vị đắng đậm đà của cà phê thì không thể bỏ qua món đồ uống này.',
        //            'product_image'=>'uploads/image/products/ca-phe-cot-dua.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_011',
        //            'categories_id' => 2,
        //            'product_name'=> 'Freeze Trà Xanh',
        //            'product_slug'=>'',
        //            'product_description'=> 'Thức uống rất được ưa chuộng! Trà xanh thượng hạng từ cao nguyên Việt Nam, kết hợp cùng đá xay, thạch trà dai dai, thơm ngon và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Trà Xanh thơm ngon, mát lạnh, chinh phục bất cứ ai!',
        //            'product_image'=>'uploads/image/products/freeze-tra-xanh.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_012',
        //            'categories_id' => 2,
        //            'product_name'=> 'Freeze Socola',
        //            'product_slug'=>'',
        //            'product_description'=> 'Thiên đường đá xay sô cô la! Từ những thanh sô cô la Việt Nam chất lượng được đem xay với đá cho đến khi mềm mịn, sau đó thêm vào thạch sô cô la dai giòn, ở trên được phủ một lớp kem whip beo béo và sốt sô cô la ngọt ngào. Tạo thành Freeze Sô-cô-la ngon mê mẩn chinh phục bất kì ai!',
        //            'product_image'=>'uploads/image/products/freeze-socola.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_013',
        //            'categories_id' => 2,
        //            'product_name'=> 'Freeze Việt Quất',
        //            'product_slug'=>'',
        //            'product_description'=> 'Thức uống rất được ưa chuộng! Việt quất thượng hạngkết hợp cùng đá xay, sốt Việt Quất, thơm ngon và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Việt Quất thơm ngon, mát lạnh, chinh phục bất cứ ai!',
        //            'product_image'=>'uploads/image/products/freeze-viet-quat.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_014',
        //            'categories_id' => 2,
        //            'product_name'=> 'Freeze KiWi',
        //            'product_slug'=>'',
        //            'product_description'=> 'Thức uống rất được ưa chuộng! Kiwi thượng hạng kết hợp cùng đá xay, sốt Kiwi, thơm ngon và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Kiwi thơm ngon, mát lạnh, chinh phục bất cứ ai!',
        //            'product_image'=>'uploads/image/products/freeze-tra-xanh.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_015',
        //            'categories_id' => 2,
        //            'product_name'=> 'Caramel Phin Freeze',
        //            'product_slug'=>'',
        //            'product_description'=> 'Thơm ngon khó cưỡng! Được kết hợp từ cà phê truyền thống chỉ có tại Highlands Coffee, cùng với caramel, thạch cà phê và đá xay mát lạnh. Trên cùng là lớp kem tươi thơm béo và caramel ngọt ngào. Món nước phù hợp trong những cuộc gặp gỡ bạn bè, bởi sự ngọt ngào thường mang mọi người xích lại gần nhau.',
        //            'product_image'=>'uploads/image/products/caramel-freeze.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_016',
        //            'categories_id' => 2,
        //            'product_name'=> 'Freeze Cacao',
        //            'product_slug'=>'',
        //            'product_description'=> 'Thơm ngon đậm đà! Được kết hợp từ cà phê pha Phin truyền thống chỉ có tại Highlands Coffee, cùng với thạch cà phê và đá xay mát lạnh. Trên cùng là lớp kem tươi thơm béo và bột ca cao đậm đà. Món nước hoàn hảo để khởi đầu câu chuyện cùng bạn bè.',
        //            'product_image'=>'uploads/image/products/freeze-cacao.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_017',
        //            'categories_id' => 2,
        //            'product_name'=> 'Freeze Trà Đào',
        //            'product_slug'=>'',
        //            'product_description'=> 'Thức uống rất được ưa chuộng! Đào thượng hạng kết hợp cùng đá xay, thạch đào dai dai, thơm ngon và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Trà Đào thơm ngon, mát lạnh, chinh phục bất cứ ai!',
        //            'product_image'=>'uploads/image/products/freeze-tra-dao.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_018',
        //            'categories_id' => 2,
        //            'product_name'=> 'Freeze Dâu Tây',
        //            'product_slug'=>'',
        //            'product_description'=> 'Thức uống rất được ưa chuộng! Dâu thượng hạng kết hợp cùng đá xay, mứt dâu dai dai, thơm ngon với sữa chua tuyệt hảo và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Dâu Tây thơm ngon, mát lạnh, chinh phục bất cứ ai!',
        //            'product_image'=>'uploads/image/products/freeze-dau-tay.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_019',
        //            'categories_id' => 3,
        //            'product_name'=> 'Bánh Tiramisu',
        //            'product_slug'=>'',
        //            'product_description'=> 'Tiramisu là một loại bánh ngọt tráng miệng vị cà phê của nước Ý, gồm các lớp bánh quy Savoiardi, [savoˈjardi] nhúng cà phê xen kẽ với hỗn hợp trứng, đường, phô mai mascarpone đánh bông, thêm một ít bột cacao. Công thức bánh này được biến tấu thành nhiều món bánh và món tráng miệng khác nhau.',
        //            'product_image'=>'uploads/image/products/banh-tiramisu.jfif',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_020',
        //            'categories_id' => 3,
        //            'product_name'=> 'Bánh CheeseCake Caramel',
        //            'product_slug'=>'',
        //            'product_description'=> 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn, cafe và Caramel hảo hạn',
        //            'product_image'=>'uploads/image/products/chessecake-caramel.jfif',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_021',
        //            'categories_id' => 3,
        //            'product_name'=> 'Bánh CheeseCake Cam',
        //            'product_slug'=>'',
        //            'product_description'=> 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn và Cam hảo hạn',
        //            'product_image'=>'uploads/image/products/chessecake-cam.jfif',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_022',
        //            'categories_id' => 3,
        //            'product_name'=> 'Bánh CheeseCake Đào',
        //            'product_slug'=>'',
        //            'product_description'=> 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn và Đào hảo hạn',
        //            'product_image'=>'uploads/image/products/chessecake-dao.jfif',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_023',
        //            'categories_id' => 3,
        //            'product_name'=> 'Bánh CheeseCake Việt Quất',
        //            'product_slug'=>'',
        //            'product_description'=> 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn và Việt Quất hảo hạn',
        //            'product_image'=>'uploads/image/products/chessecake-viet-quat.jfif',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_024',
        //            'categories_id' => 3,
        //            'product_name'=> 'Bánh CheeseCake Matcha',
        //            'product_slug'=>'',
        //            'product_description'=> 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn và Matcha hảo hạn',
        //            'product_image'=>'uploads/image/products/chessecake-matcha.jfif',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_025',
        //            'categories_id' => 5,
        //            'product_name'=> 'Trà Đào Cam Sả',
        //            'product_slug'=>'',
        //            'product_description'=> 'Vị thanh ngọt của đào Hy Lạp, vị chua dịu của Cam Vàng nguyên vỏ, vị chát của trà đen tươi được ủ mới mỗi 4 tiếng, cùng hương thơm nồng đặc trưng của sả chính là điểm sáng làm nên sức hấp dẫn của thức uống này. Sản phẩm hiện có 2 phiên bản Nóng và Lạnh phù hợp cho mọi thời gian trong năm.',
        //            'product_image'=>'uploads/image/products/tra-thanh-dao.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_026',
        //            'categories_id' => 5,
        //            'product_name'=> 'Trà Thanh Đào',
        //            'product_slug'=>'',
        //            'product_description'=> 'Một trải nghiệm thú vị khác! Sự hài hòa giữa vị trà cao cấp, vị sả thanh mát và những miếng đào thơm ngon mọng nước sẽ mang đến cho bạn một thức uống tuyệt vời.',
        //            'product_image'=>'uploads/image/products/tra-thanh-dao.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_027',
        //            'categories_id' => 5,
        //            'product_name'=> 'Trà Thạch Đào',
        //            'product_slug'=>'',
        //            'product_description'=> 'Vị trà đậm đà kết hợp cùng những miếng đào thơm ngon mọng nước cùng thạch đào giòn dai. Thêm vào ít sữa để gia tăng vị béo.',
        //            'product_image'=>'uploads/image/products/tra-thach-dao.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_028',
        //            'categories_id' => 5,
        //            'product_name'=> 'Trà Sen Vàng',
        //            'product_slug'=>'',
        //            'product_description'=> 'Thức uống chinh phục những thực khách khó tính! Sự kết hợp độc đáo giữa trà Ô long, hạt sen thơm bùi và củ năng giòn tan. Thêm vào chút sữa sẽ để vị thêm ngọt ngào.',
        //            'product_image'=>'uploads/image/products/tra-sen-vang.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_029',
        //            'categories_id' => 5,
        //            'product_name'=> 'Trà Thạch Vải',
        //            'product_slug'=>'',
        //            'product_description'=> 'Một sự kết hợp thú vị giữa trà đen, những quả vải thơm ngon và thạch giòn khó cưỡng, mang đến thức uống tuyệt hảo!',
        //            'product_image'=>'uploads/image/products/tra-thach-vai.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_030',
        //            'categories_id' => 5,
        //            'product_name'=> 'Trà Đào Dầm',
        //            'product_slug'=>'',
        //            'product_description'=> 'Một sự kết hợp thú vị giữa trà đen, sốt đào thơm ngon và đào miếng khó cưỡng, mang đến thức uống tuyệt hảo!',
        //            'product_image'=>'uploads/image/products/tra-dao-dam.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_031',
        //            'categories_id' => 4,
        //            'product_name'=> 'Pizza Bò Ngô',
        //            'product_slug'=>'',
        //            'product_description'=> 'Vị chua chua, ngọt ngọt của dứa kết hợp với vỏ bánh giòn xốp cùng với thịt bò băm có thể tạo nên hương vị pizza đặc trưng khiến bạn nhớ mãi chẳng quên. Cũng bởi vậy mà pizza bò băm luôn là "best-seller" trong menu của các tiệm bánh pizza nổi tiếng.',
        //            'product_image'=>'uploads/image/products/pizza-bo-ngo.jfif',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_032',
        //            'categories_id' => 4,
        //            'product_name'=> 'Pizza Hải Sản',
        //            'product_slug'=>'',
        //            'product_description'=> 'Vị dai giòn sần sật của mực xen lẫn vị ngọt của tôm sú quyện hương phô mai cùng rau củ thơm ngon, dễ ăn và dễ đi vào lòng người ở mọi lứa tuổi nhất cực yêu thích.',
        //            'product_image'=>'uploads/image/products/pizza-hai-san.jfif',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_033',
        //            'categories_id' => 4,
        //            'product_name'=> 'Hướng Dương Nguyên Vị',
        //            'product_slug'=>'',
        //            'product_description'=> '',
        //            'product_image'=>'uploads/image/products/huong-duong-thuong.jfif',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ],
        //        [
        //         //    'product_id' => 'product_034',
        //            'categories_id' => 4,
        //            'product_name'=> 'Hướng Dương Vị Dừa',
        //            'product_slug'=>'',
        //            'product_description'=> '',
        //            'product_image'=>'uploads/image/products/huong-duong-dua.jpg',
        //            'product_unit'=>'Cốc',
        //            'product_amout_imports'=> 30,
        //            'product_amout_sales'=> 30,
        //        ]
        //    ]


        // ['id' => '1','categories_id' => '7','product_name' => 'Cà Phê Sữa Đá','product_slug' => 'ca-phe-sua-da','product_description' => 'Hương vị cà phê Việt Nam đích thực! Từng hạt cà phê hảo hạng được chọn bằng tay, phối trộn độc đáo giữa hạt Robusta từ cao nguyên Việt Nam, thêm Arabica thơm lừng. Cà phê được pha từ Phin truyền thống, hoà cùng sữa đặc sánh và thêm vào chút đá tạo nên ly Phin Sữa Đá – Đậm Đà Chất Phin.','product_image' => 'uploads/image/products/ca-phe-sua-da.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '2','categories_id' => '7','product_name' => 'Cà Phê Đen Đá','product_slug' => 'ca-phe-den-da','product_description' => 'Dành cho những tín đồ cà phê đích thực! Hương vị cà phê truyền thống được phối trộn độc đáo tại Highlands. Cà phê đậm đà pha hoàn toàn từ Phin, cho thêm 1 thìa đường, một ít đá viên mát lạnh, tạo nên Phin Đen Đá mang vị cà phê đậm đà chất Phin. ','product_image' => 'uploads/image/products/ca-phe-den-da.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '3','categories_id' => '7','product_name' => 'Cà Phê Đen Nóng','product_slug' => 'ca-phe-den-nong','product_description' => 'Dành cho những tín đồ cà phê đích thực! Hương vị cà phê truyền thống được phối trộn độc đáo tại Highlands. Cà phê đậm đà pha từ Phin, cho thêm 1 thìa đường, mang đến vị cà phê đậm đà chất Phin. ','product_image' => 'uploads/image/products/ca-phe-den-da.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '4','categories_id' => '7','product_name' => 'Cà Phê Sữa Nóng','product_slug' => 'ca-phe-sua-nong','product_description' => 'Hương vị cà phê Việt Nam đích thực! Từng hạt cà phê hảo hạng được chọn bằng tay, phối trộn độc đáo giữa hạt Robusta từ cao nguyên Việt Nam, thêm Arabica thơm lừng. Kết hợp với nước sôi từng giọt cà phê được chiết xuất từ Phin truyền thống, hoà cùng sữa đặc sánh tạo nên ly Phin Sữa Nóng – Đậm đà chất Phin.','product_image' => 'uploads/image/products/ca-phe-sua-da.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '5','categories_id' => '6','product_name' => 'PhiDi Kem Sữa','product_slug' => 'phidi-kem-sua','product_description' => 'PhinDi Kem Sữa - Cà phê Phin thế hệ mới với chất Phin êm hơn, kết hợp cùng Kem Sữa béo ngậy mang đến hương vị mới lạ, không thể hấp dẫn hơn!','product_image' => 'uploads/image/products/phi-di-kem-sua.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '6','categories_id' => '6','product_name' => 'PhiDi Choco','product_slug' => 'phidi-choco','product_description' => 'PhinDi Choco - Cà phê Phin thế hệ mới với chất Phin êm hơn, kết hợp cùng Choco ngọt tan mang đến hương vị mới lạ, không thể hấp dẫn hơn!','product_image' => 'uploads/image/products/phi-di-cho-co.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '7','categories_id' => '6','product_name' => 'Cà Phê Sữa Chua','product_slug' => 'ca-phe-sua-chua','product_description' => 'Nhâm nhi một tách cà phê mỗi ngày là cách tiếp thêm năng lượng tích cực của nhiều thế hệ người Việt Nam. Để hương vị cà phê truyền thống không nhàm chán, bạn có thể học cách pha cafe sữa chua của chúng tôi. Đây là sự kết hợp hoàn hảo, mang đến hương vị thanh mát mới lạ, lại có lợi cho sức khỏe, hệ tiêu hóa của bạn đấy! ','product_image' => 'uploads/image/products/bac-xiu.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '8','categories_id' => '6','product_name' => 'Cà Phê Trứng','product_slug' => 'ca-phe-trung','product_description' => 'Nếu là người Hà thành hay là những người sành và yêu thích cafe thì chắc hẳn bạn không còn xa lạ gì với món cafe trứng nữa rồi. Được chế biến và khởi nguồn đầu tiên từ Hà Nội, đến nay cafe trứng dường như còn nổi danh trên khắp thế giới thu hút rất nhiều du khách đến thưởng thức.','product_image' => 'uploads/image/products/ca-phe-sua-da.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '9','categories_id' => '6','product_name' => 'Bạc Xỉu','product_slug' => 'bac-xiu','product_description' => 'Nếu Phin Sữa Đá dành cho các bạn đam mê vị đậm đà, thì Bạc Xỉu Đá là một sự lựa chọn nhẹ “đô" cà phê nhưng vẫn thơm ngon, chất lừ không kém!','product_image' => 'uploads/image/products/bac-xiu.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '10','categories_id' => '6','product_name' => 'Cà Phê Cốt Dừa','product_slug' => 'ca-phe-cot-dua','product_description' => 'Bạn có phải là fan của món cafe cốt dừa vô cùng nổi tiếng của Cộng cà phê? Với những ai yêu cà phê và thích thú với hương vị béo ngậy của dừa hòa quyện với vị đắng đậm đà của cà phê thì không thể bỏ qua món đồ uống này.','product_image' => 'uploads/image/products/ca-phe-cot-dua.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '11','categories_id' => '2','product_name' => 'Freeze Trà Xanh','product_slug' => 'freeze-tra-xanh','product_description' => 'Thức uống rất được ưa chuộng! Trà xanh thượng hạng từ cao nguyên Việt Nam, kết hợp cùng đá xay, thạch trà dai dai, thơm ngon và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Trà Xanh thơm ngon, mát lạnh, chinh phục bất cứ ai!','product_image' => 'uploads/image/products/freeze-tra-xanh.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '12','categories_id' => '2','product_name' => 'Freeze Socola','product_slug' => 'freeze-socola','product_description' => 'Thiên đường đá xay sô cô la! Từ những thanh sô cô la Việt Nam chất lượng được đem xay với đá cho đến khi mềm mịn, sau đó thêm vào thạch sô cô la dai giòn, ở trên được phủ một lớp kem whip beo béo và sốt sô cô la ngọt ngào. Tạo thành Freeze Sô-cô-la ngon mê mẩn chinh phục bất kì ai!','product_image' => 'uploads/image/products/freeze-socola.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '13','categories_id' => '2','product_name' => 'Freeze Việt Quất','product_slug' => 'freeze-viet-quat','product_description' => 'Thức uống rất được ưa chuộng! Việt quất thượng hạngkết hợp cùng đá xay, sốt Việt Quất, thơm ngon và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Việt Quất thơm ngon, mát lạnh, chinh phục bất cứ ai!','product_image' => 'uploads/image/products/freeze-viet-quat.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '14','categories_id' => '2','product_name' => 'Freeze KiWi','product_slug' => 'freeze-kiwi','product_description' => 'Thức uống rất được ưa chuộng! Kiwi thượng hạng kết hợp cùng đá xay, sốt Kiwi, thơm ngon và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Kiwi thơm ngon, mát lạnh, chinh phục bất cứ ai!','product_image' => 'uploads/image/products/freeze-tra-xanh.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '15','categories_id' => '2','product_name' => 'Caramel Phin Freeze','product_slug' => 'caramel-phin-freeze','product_description' => 'Thơm ngon khó cưỡng! Được kết hợp từ cà phê truyền thống chỉ có tại Highlands Coffee, cùng với caramel, thạch cà phê và đá xay mát lạnh. Trên cùng là lớp kem tươi thơm béo và caramel ngọt ngào. Món nước phù hợp trong những cuộc gặp gỡ bạn bè, bởi sự ngọt ngào thường mang mọi người xích lại gần nhau.','product_image' => 'uploads/image/products/caramel-freeze.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '16','categories_id' => '2','product_name' => 'Freeze Cacao','product_slug' => 'freeze-cacao','product_description' => 'Thơm ngon đậm đà! Được kết hợp từ cà phê pha Phin truyền thống chỉ có tại Highlands Coffee, cùng với thạch cà phê và đá xay mát lạnh. Trên cùng là lớp kem tươi thơm béo và bột ca cao đậm đà. Món nước hoàn hảo để khởi đầu câu chuyện cùng bạn bè.','product_image' => 'uploads/image/products/freeze-cacao.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '17','categories_id' => '2','product_name' => 'Freeze Trà Đào','product_slug' => 'freeze-tra-dao','product_description' => 'Thức uống rất được ưa chuộng! Đào thượng hạng kết hợp cùng đá xay, thạch đào dai dai, thơm ngon và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Trà Đào thơm ngon, mát lạnh, chinh phục bất cứ ai!','product_image' => 'uploads/image/products/freeze-tra-dao.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '18','categories_id' => '2','product_name' => 'Freeze Dâu Tây','product_slug' => 'freeze-dau-tay','product_description' => 'Thức uống rất được ưa chuộng! Dâu thượng hạng kết hợp cùng đá xay, mứt dâu dai dai, thơm ngon với sữa chua tuyệt hảo và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Dâu Tây thơm ngon, mát lạnh, chinh phục bất cứ ai!','product_image' => 'uploads/image/products/freeze-dau-tay.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '19','categories_id' => '3','product_name' => 'Bánh Tiramisu','product_slug' => 'banh-tiramisu','product_description' => 'Tiramisu là một loại bánh ngọt tráng miệng vị cà phê của nước Ý, gồm các lớp bánh quy Savoiardi, [savoˈjardi] nhúng cà phê xen kẽ với hỗn hợp trứng, đường, phô mai mascarpone đánh bông, thêm một ít bột cacao. Công thức bánh này được biến tấu thành nhiều món bánh và món tráng miệng khác nhau.','product_image' => 'uploads/image/products/banh-tiramisu.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '20','categories_id' => '3','product_name' => 'Bánh CheeseCake Caramel','product_slug' => 'banh-cheesecake-caramel','product_description' => 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn, cafe và Caramel hảo hạn','product_image' => 'uploads/image/products/chessecake-caramel.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '21','categories_id' => '3','product_name' => 'Bánh CheeseCake Cam','product_slug' => 'banh-cheesecake-cam','product_description' => 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn và Cam hảo hạn','product_image' => 'uploads/image/products/chessecake-cam.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '22','categories_id' => '3','product_name' => 'Bánh CheeseCake Đào','product_slug' => 'banh-cheesecake-dao','product_description' => 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn và Đào hảo hạn','product_image' => 'uploads/image/products/chessecake-dao.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '23','categories_id' => '3','product_name' => 'Bánh CheeseCake Việt Quất','product_slug' => 'banh-cheesecake-viet-quat','product_description' => 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn và Việt Quất hảo hạn','product_image' => 'uploads/image/products/chessecake-viet-quat.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '24','categories_id' => '3','product_name' => 'Bánh CheeseCake Matcha','product_slug' => 'banh-cheesecake-matcha','product_description' => 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn và Matcha hảo hạn','product_image' => 'uploads/image/products/chessecake-matcha.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '25','categories_id' => '5','product_name' => 'Trà Đào Cam Sả','product_slug' => 'tra-dao-cam-sa','product_description' => 'Vị thanh ngọt của đào Hy Lạp, vị chua dịu của Cam Vàng nguyên vỏ, vị chát của trà đen tươi được ủ mới mỗi 4 tiếng, cùng hương thơm nồng đặc trưng của sả chính là điểm sáng làm nên sức hấp dẫn của thức uống này. Sản phẩm hiện có 2 phiên bản Nóng và Lạnh phù hợp cho mọi thời gian trong năm.','product_image' => 'uploads/image/products/tra-thanh-dao.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '26','categories_id' => '5','product_name' => 'Trà Thanh Đào','product_slug' => 'tra-thanh-dao','product_description' => 'Một trải nghiệm thú vị khác! Sự hài hòa giữa vị trà cao cấp, vị sả thanh mát và những miếng đào thơm ngon mọng nước sẽ mang đến cho bạn một thức uống tuyệt vời.','product_image' => 'uploads/image/products/tra-thanh-dao.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '27','categories_id' => '5','product_name' => 'Trà Thạch Đào','product_slug' => 'tra-thach-dao','product_description' => 'Vị trà đậm đà kết hợp cùng những miếng đào thơm ngon mọng nước cùng thạch đào giòn dai. Thêm vào ít sữa để gia tăng vị béo.','product_image' => 'uploads/image/products/tra-thach-dao.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '28','categories_id' => '5','product_name' => 'Trà Sen Vàng','product_slug' => 'tra-sen-vang','product_description' => 'Thức uống chinh phục những thực khách khó tính! Sự kết hợp độc đáo giữa trà Ô long, hạt sen thơm bùi và củ năng giòn tan. Thêm vào chút sữa sẽ để vị thêm ngọt ngào.','product_image' => 'uploads/image/products/tra-sen-vang.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '29','categories_id' => '5','product_name' => 'Trà Thạch Vải','product_slug' => 'tra-thach-vai','product_description' => 'Một sự kết hợp thú vị giữa trà đen, những quả vải thơm ngon và thạch giòn khó cưỡng, mang đến thức uống tuyệt hảo!','product_image' => 'uploads/image/products/tra-thach-vai.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '30','categories_id' => '5','product_name' => 'Trà Đào Dầm','product_slug' => 'tra-dao-dam','product_description' => 'Một sự kết hợp thú vị giữa trà đen, sốt đào thơm ngon và đào miếng khó cưỡng, mang đến thức uống tuyệt hảo!','product_image' => 'uploads/image/products/tra-dao-dam.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '31','categories_id' => '4','product_name' => 'Pizza Bò Ngô','product_slug' => 'pizza-bo-ngo','product_description' => 'Vị chua chua, ngọt ngọt của dứa kết hợp với vỏ bánh giòn xốp cùng với thịt bò băm có thể tạo nên hương vị pizza đặc trưng khiến bạn nhớ mãi chẳng quên. Cũng bởi vậy mà pizza bò băm luôn là "best-seller" trong menu của các tiệm bánh pizza nổi tiếng.','product_image' => 'uploads/image/products/pizza-bo-ngo.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '32','categories_id' => '4','product_name' => 'Pizza Hải Sản','product_slug' => 'pizza-hai-san','product_description' => 'Vị dai giòn sần sật của mực xen lẫn vị ngọt của tôm sú quyện hương phô mai cùng rau củ thơm ngon, dễ ăn và dễ đi vào lòng người ở mọi lứa tuổi nhất cực yêu thích.','product_image' => 'uploads/image/products/pizza-hai-san.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '33','categories_id' => '4','product_name' => 'Hướng Dương Nguyên Vị','product_slug' => 'huong-duong-nguyen-vi','product_description' => '','product_image' => 'uploads/image/products/huong-duong-thuong.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'],
  ['id' => '34','categories_id' => '4','product_name' => 'Hướng Dương Vị Dừa','product_slug' => 'huong-duong-vi-dua','product_description' => '','product_image' => 'uploads/image/products/huong-duong-dua.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53']
            ]
       );
    }
}
