<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.1.0
 */

/**
 * Database `hat882020`
 */

/* `hat882020`.`bill_details` */
$bill_details = array(
  array('id' => '1','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '2','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '3','product_id' => '13','product_quantity' => '1','product_total' => '35000','bill_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '4','product_id' => '14','product_quantity' => '4','product_total' => '140000','bill_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '5','product_id' => '16','product_quantity' => '1','product_total' => '35000','bill_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '6','product_id' => '17','product_quantity' => '1','product_total' => '35000','bill_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '7','product_id' => '15','product_quantity' => '1','product_total' => '35000','bill_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '8','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '2','created_at' => NULL,'updated_at' => NULL),
  array('id' => '9','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '2','created_at' => NULL,'updated_at' => NULL),
  array('id' => '10','product_id' => '13','product_quantity' => '1','product_total' => '35000','bill_id' => '2','created_at' => NULL,'updated_at' => NULL),
  array('id' => '11','product_id' => '14','product_quantity' => '4','product_total' => '140000','bill_id' => '2','created_at' => NULL,'updated_at' => NULL),
  array('id' => '12','product_id' => '16','product_quantity' => '1','product_total' => '35000','bill_id' => '2','created_at' => NULL,'updated_at' => NULL),
  array('id' => '13','product_id' => '17','product_quantity' => '1','product_total' => '35000','bill_id' => '2','created_at' => NULL,'updated_at' => NULL),
  array('id' => '14','product_id' => '15','product_quantity' => '1','product_total' => '35000','bill_id' => '2','created_at' => NULL,'updated_at' => NULL),
  array('id' => '15','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '16','product_id' => '13','product_quantity' => '1','product_total' => '35000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '17','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '18','product_id' => '14','product_quantity' => '1','product_total' => '35000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '19','product_id' => '5','product_quantity' => '1','product_total' => '35000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '20','product_id' => '6','product_quantity' => '1','product_total' => '35000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '21','product_id' => '21','product_quantity' => '1','product_total' => '25000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '22','product_id' => '19','product_quantity' => '1','product_total' => '25000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '23','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '4','created_at' => NULL,'updated_at' => NULL),
  array('id' => '24','product_id' => '14','product_quantity' => '1','product_total' => '35000','bill_id' => '4','created_at' => NULL,'updated_at' => NULL),
  array('id' => '25','product_id' => '16','product_quantity' => '1','product_total' => '35000','bill_id' => '5','created_at' => NULL,'updated_at' => NULL),
  array('id' => '26','product_id' => '18','product_quantity' => '1','product_total' => '35000','bill_id' => '5','created_at' => NULL,'updated_at' => NULL),
  array('id' => '27','product_id' => '11','product_quantity' => '4','product_total' => '140000','bill_id' => '6','created_at' => NULL,'updated_at' => NULL),
  array('id' => '28','product_id' => '5','product_quantity' => '4','product_total' => '140000','bill_id' => '6','created_at' => NULL,'updated_at' => NULL),
  array('id' => '29','product_id' => '6','product_quantity' => '3','product_total' => '105000','bill_id' => '6','created_at' => NULL,'updated_at' => NULL),
  array('id' => '30','product_id' => '11','product_quantity' => '3','product_total' => '105000','bill_id' => '7','created_at' => NULL,'updated_at' => NULL),
  array('id' => '31','product_id' => '14','product_quantity' => '3','product_total' => '105000','bill_id' => '7','created_at' => NULL,'updated_at' => NULL),
  array('id' => '32','product_id' => '12','product_quantity' => '3','product_total' => '105000','bill_id' => '7','created_at' => NULL,'updated_at' => NULL),
  array('id' => '33','product_id' => '11','product_quantity' => '3','product_total' => '105000','bill_id' => '8','created_at' => NULL,'updated_at' => NULL),
  array('id' => '34','product_id' => '14','product_quantity' => '3','product_total' => '105000','bill_id' => '8','created_at' => NULL,'updated_at' => NULL),
  array('id' => '35','product_id' => '12','product_quantity' => '3','product_total' => '105000','bill_id' => '8','created_at' => NULL,'updated_at' => NULL),
  array('id' => '36','product_id' => '18','product_quantity' => '1','product_total' => '35000','bill_id' => '9','created_at' => NULL,'updated_at' => NULL),
  array('id' => '37','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '10','created_at' => NULL,'updated_at' => NULL),
  array('id' => '38','product_id' => '13','product_quantity' => '1','product_total' => '35000','bill_id' => '10','created_at' => NULL,'updated_at' => NULL),
  array('id' => '39','product_id' => '15','product_quantity' => '1','product_total' => '35000','bill_id' => '10','created_at' => NULL,'updated_at' => NULL),
  array('id' => '40','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '11','created_at' => NULL,'updated_at' => NULL),
  array('id' => '41','product_id' => '13','product_quantity' => '1','product_total' => '35000','bill_id' => '11','created_at' => NULL,'updated_at' => NULL),
  array('id' => '42','product_id' => '18','product_quantity' => '1','product_total' => '35000','bill_id' => '11','created_at' => NULL,'updated_at' => NULL),
  array('id' => '43','product_id' => '23','product_quantity' => '1','product_total' => '25000','bill_id' => '11','created_at' => NULL,'updated_at' => NULL),
  array('id' => '44','product_id' => '21','product_quantity' => '1','product_total' => '25000','bill_id' => '11','created_at' => NULL,'updated_at' => NULL),
  array('id' => '45','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '12','created_at' => NULL,'updated_at' => NULL),
  array('id' => '46','product_id' => '14','product_quantity' => '1','product_total' => '35000','bill_id' => '12','created_at' => NULL,'updated_at' => NULL),
  array('id' => '47','product_id' => '13','product_quantity' => '2','product_total' => '70000','bill_id' => '13','created_at' => NULL,'updated_at' => NULL),
  array('id' => '48','product_id' => '15','product_quantity' => '3','product_total' => '105000','bill_id' => '13','created_at' => NULL,'updated_at' => NULL),
  array('id' => '49','product_id' => '18','product_quantity' => '3','product_total' => '105000','bill_id' => '13','created_at' => NULL,'updated_at' => NULL),
  array('id' => '50','product_id' => '16','product_quantity' => '3','product_total' => '105000','bill_id' => '13','created_at' => NULL,'updated_at' => NULL),
  array('id' => '51','product_id' => '17','product_quantity' => '3','product_total' => '105000','bill_id' => '13','created_at' => NULL,'updated_at' => NULL),
  array('id' => '52','product_id' => '5','product_quantity' => '3','product_total' => '105000','bill_id' => '13','created_at' => NULL,'updated_at' => NULL),
  array('id' => '53','product_id' => '7','product_quantity' => '3','product_total' => '87000','bill_id' => '13','created_at' => NULL,'updated_at' => NULL),
  array('id' => '54','product_id' => '18','product_quantity' => '1','product_total' => '35000','bill_id' => '14','created_at' => NULL,'updated_at' => NULL),
  array('id' => '55','product_id' => '17','product_quantity' => '1','product_total' => '35000','bill_id' => '14','created_at' => NULL,'updated_at' => NULL),
  array('id' => '56','product_id' => '16','product_quantity' => '1','product_total' => '35000','bill_id' => '14','created_at' => NULL,'updated_at' => NULL),
  array('id' => '57','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '15','created_at' => NULL,'updated_at' => NULL),
  array('id' => '58','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '15','created_at' => NULL,'updated_at' => NULL),
  array('id' => '59','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '15','created_at' => NULL,'updated_at' => NULL),
  array('id' => '60','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '16','created_at' => NULL,'updated_at' => NULL),
  array('id' => '61','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '16','created_at' => NULL,'updated_at' => NULL),
  array('id' => '62','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '16','created_at' => NULL,'updated_at' => NULL),
  array('id' => '63','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '17','created_at' => NULL,'updated_at' => NULL),
  array('id' => '64','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '17','created_at' => NULL,'updated_at' => NULL),
  array('id' => '65','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '17','created_at' => NULL,'updated_at' => NULL),
  array('id' => '66','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '18','created_at' => NULL,'updated_at' => NULL),
  array('id' => '67','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '18','created_at' => NULL,'updated_at' => NULL),
  array('id' => '68','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '18','created_at' => NULL,'updated_at' => NULL),
  array('id' => '69','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '19','created_at' => NULL,'updated_at' => NULL),
  array('id' => '70','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '19','created_at' => NULL,'updated_at' => NULL),
  array('id' => '71','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '19','created_at' => NULL,'updated_at' => NULL),
  array('id' => '72','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '20','created_at' => NULL,'updated_at' => NULL),
  array('id' => '73','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '20','created_at' => NULL,'updated_at' => NULL),
  array('id' => '74','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '20','created_at' => NULL,'updated_at' => NULL),
  array('id' => '75','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '21','created_at' => NULL,'updated_at' => NULL),
  array('id' => '76','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '21','created_at' => NULL,'updated_at' => NULL),
  array('id' => '77','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '21','created_at' => NULL,'updated_at' => NULL),
  array('id' => '78','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '22','created_at' => NULL,'updated_at' => NULL),
  array('id' => '79','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '22','created_at' => NULL,'updated_at' => NULL),
  array('id' => '80','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '22','created_at' => NULL,'updated_at' => NULL),
  array('id' => '81','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '23','created_at' => NULL,'updated_at' => NULL),
  array('id' => '82','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '23','created_at' => NULL,'updated_at' => NULL),
  array('id' => '83','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '23','created_at' => NULL,'updated_at' => NULL),
  array('id' => '84','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '24','created_at' => NULL,'updated_at' => NULL),
  array('id' => '85','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '24','created_at' => NULL,'updated_at' => NULL),
  array('id' => '86','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '24','created_at' => NULL,'updated_at' => NULL),
  array('id' => '87','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '25','created_at' => NULL,'updated_at' => NULL),
  array('id' => '88','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '25','created_at' => NULL,'updated_at' => NULL),
  array('id' => '89','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '25','created_at' => NULL,'updated_at' => NULL),
  array('id' => '90','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '26','created_at' => NULL,'updated_at' => NULL),
  array('id' => '91','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '26','created_at' => NULL,'updated_at' => NULL),
  array('id' => '92','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '26','created_at' => NULL,'updated_at' => NULL),
  array('id' => '93','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '27','created_at' => NULL,'updated_at' => NULL),
  array('id' => '94','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '27','created_at' => NULL,'updated_at' => NULL),
  array('id' => '95','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '27','created_at' => NULL,'updated_at' => NULL),
  array('id' => '96','product_id' => '15','product_quantity' => '1','product_total' => '35000','bill_id' => '28','created_at' => NULL,'updated_at' => NULL),
  array('id' => '97','product_id' => '17','product_quantity' => '1','product_total' => '35000','bill_id' => '28','created_at' => NULL,'updated_at' => NULL),
  array('id' => '98','product_id' => '16','product_quantity' => '1','product_total' => '35000','bill_id' => '28','created_at' => NULL,'updated_at' => NULL),
  array('id' => '99','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '29','created_at' => NULL,'updated_at' => NULL),
  array('id' => '100','product_id' => '18','product_quantity' => '1','product_total' => '35000','bill_id' => '29','created_at' => NULL,'updated_at' => NULL),
  array('id' => '101','product_id' => '32','product_quantity' => '2','product_total' => '98000','bill_id' => '29','created_at' => NULL,'updated_at' => NULL),
  array('id' => '102','product_id' => '31','product_quantity' => '2','product_total' => '90000','bill_id' => '29','created_at' => NULL,'updated_at' => NULL),
  array('id' => '103','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '30','created_at' => NULL,'updated_at' => NULL),
  array('id' => '104','product_id' => '16','product_quantity' => '3','product_total' => '105000','bill_id' => '30','created_at' => NULL,'updated_at' => NULL),
  array('id' => '105','product_id' => '14','product_quantity' => '1','product_total' => '35000','bill_id' => '30','created_at' => NULL,'updated_at' => NULL),
  array('id' => '106','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '30','created_at' => NULL,'updated_at' => NULL),
  array('id' => '107','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '31','created_at' => NULL,'updated_at' => NULL),
  array('id' => '108','product_id' => '16','product_quantity' => '3','product_total' => '105000','bill_id' => '31','created_at' => NULL,'updated_at' => NULL),
  array('id' => '109','product_id' => '14','product_quantity' => '1','product_total' => '35000','bill_id' => '31','created_at' => NULL,'updated_at' => NULL),
  array('id' => '110','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '31','created_at' => NULL,'updated_at' => NULL),
  array('id' => '111','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '32','created_at' => NULL,'updated_at' => NULL),
  array('id' => '112','product_id' => '13','product_quantity' => '1','product_total' => '35000','bill_id' => '32','created_at' => NULL,'updated_at' => NULL),
  array('id' => '113','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '32','created_at' => NULL,'updated_at' => NULL),
  array('id' => '114','product_id' => '14','product_quantity' => '1','product_total' => '35000','bill_id' => '32','created_at' => NULL,'updated_at' => NULL),
  array('id' => '115','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '33','created_at' => NULL,'updated_at' => NULL),
  array('id' => '116','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '33','created_at' => NULL,'updated_at' => NULL),
  array('id' => '117','product_id' => '13','product_quantity' => '1','product_total' => '35000','bill_id' => '33','created_at' => NULL,'updated_at' => NULL)
);
