<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.1.0
 */

/**
 * Database `hat882020`
 */

/* `hat882020`.`bills` */
$bills = array(
  array('id' => '1','bills_sale_day' => '2021-05-17 17:11:25','bill_pay_day' => '2021-05-21 11:06:25','bill_descriptions' => 'Nah','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '2','staff_set_bill_shipping' => '3','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '350000','bill_custormer_id' => '1','created_at' => NULL,'updated_at' => '2021-05-21 04:17:14'),
  array('id' => '2','bills_sale_day' => '2021-05-17 17:12:00','bill_pay_day' => '2021-05-21 11:13:32','bill_descriptions' => 'Ship ngay','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '3','staff_set_bill_shipping' => '6','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '350000','bill_custormer_id' => '2','created_at' => NULL,'updated_at' => '2021-05-23 07:54:36'),
  array('id' => '3','bills_sale_day' => '2021-05-17 18:20:07','bill_pay_day' => '2021-05-23 14:52:11','bill_descriptions' => 'Ship vào hôm thứ 3 tuần tới','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '5','staff_set_bill_shipping' => '5','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '260000','bill_custormer_id' => '3','created_at' => NULL,'updated_at' => '2021-05-23 07:54:20'),
  array('id' => '4','bills_sale_day' => '2021-05-17 18:27:38','bill_pay_day' => '2021-05-24 15:56:59','bill_descriptions' => 'Không có gì','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '3','staff_set_bill_ship' => '5','staff_set_bill_shipping' => '6','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '70000','bill_custormer_id' => '4','created_at' => NULL,'updated_at' => '2021-05-24 08:58:19'),
  array('id' => '5','bills_sale_day' => '2021-05-17 18:28:20','bill_pay_day' => NULL,'bill_descriptions' => 'Hay quá vậy ta','bill_state' => 'Hủy','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => '2','bill_staff_id' => NULL,'bill_total' => '70000','bill_custormer_id' => '5','created_at' => NULL,'updated_at' => '2021-05-27 09:00:04'),
  array('id' => '6','bills_sale_day' => '2021-05-17 20:38:18','bill_pay_day' => '2021-05-23 14:52:19','bill_descriptions' => 'Ship vào khu cách ly','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '3','staff_set_bill_shipping' => '5','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '385000','bill_custormer_id' => '6','created_at' => NULL,'updated_at' => '2021-05-23 07:54:19'),
  array('id' => '7','bills_sale_day' => '2021-05-23 14:43:57','bill_pay_day' => '2021-05-23 14:52:09','bill_descriptions' => 'Ship nhanh cho anh nhé','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '3','staff_set_bill_shipping' => '6','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '315000','bill_custormer_id' => '7','created_at' => NULL,'updated_at' => '2021-05-23 07:54:34'),
  array('id' => '8','bills_sale_day' => '2021-05-23 14:45:10','bill_pay_day' => '2021-05-27 15:58:54','bill_descriptions' => 'Ship nhanh cho anh nhé','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '2','staff_set_bill_shipping' => '2','staff_set_bill_done' => '2','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '315000','bill_custormer_id' => '8','created_at' => NULL,'updated_at' => '2021-05-30 05:08:28'),
  array('id' => '9','bills_sale_day' => '2021-05-23 14:49:04','bill_pay_day' => '2021-05-23 14:52:05','bill_descriptions' => 'Không','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '5','staff_set_bill_shipping' => '5','staff_set_bill_done' => '6','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '35000','bill_custormer_id' => '9','created_at' => NULL,'updated_at' => '2021-05-23 07:54:17'),
  array('id' => '10','bills_sale_day' => '2021-05-24 15:44:35','bill_pay_day' => '2021-05-24 15:56:55','bill_descriptions' => 'Không','bill_state' => 'Cần giao hàng','staff_set_bill_accepted' => '3','staff_set_bill_ship' => '2','staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '105000','bill_custormer_id' => '10','created_at' => NULL,'updated_at' => '2021-05-27 08:58:37'),
  array('id' => '11','bills_sale_day' => '2021-05-27 16:15:14','bill_pay_day' => '2021-05-27 17:16:30','bill_descriptions' => 'Không','bill_state' => 'Đang giao hàng','staff_set_bill_accepted' => '1','staff_set_bill_ship' => '2','staff_set_bill_shipping' => '2','staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '155000','bill_custormer_id' => '11','created_at' => NULL,'updated_at' => '2021-05-30 05:08:23'),
  array('id' => '12','bills_sale_day' => '2021-05-27 17:15:23','bill_pay_day' => '2021-05-30 12:08:12','bill_descriptions' => 'Không','bill_state' => 'Đã xác thực','staff_set_bill_accepted' => '2','staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '70000','bill_custormer_id' => '12','created_at' => NULL,'updated_at' => '2021-05-30 12:08:12'),
  array('id' => '13','bills_sale_day' => '2021-05-30 12:10:38','bill_pay_day' => '2021-05-30 12:10:52','bill_descriptions' => 'Ship nhanh cho mình nhé','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '2','staff_set_bill_ship' => '2','staff_set_bill_shipping' => '2','staff_set_bill_done' => '2','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '682000','bill_custormer_id' => '13','created_at' => NULL,'updated_at' => '2021-05-30 05:11:07'),
  array('id' => '14','bills_sale_day' => '2021-05-30 16:44:19','bill_pay_day' => NULL,'bill_descriptions' => 'Cảm ơn em','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '105000','bill_custormer_id' => '15','created_at' => NULL,'updated_at' => NULL),
  array('id' => '15','bills_sale_day' => '2021-05-30 17:38:07','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '16','created_at' => NULL,'updated_at' => NULL),
  array('id' => '16','bills_sale_day' => '2021-05-30 17:38:43','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '17','created_at' => NULL,'updated_at' => NULL),
  array('id' => '17','bills_sale_day' => '2021-05-30 17:38:47','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '18','created_at' => NULL,'updated_at' => NULL),
  array('id' => '18','bills_sale_day' => '2021-05-30 17:38:51','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '19','created_at' => NULL,'updated_at' => NULL),
  array('id' => '19','bills_sale_day' => '2021-05-30 17:40:01','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '20','created_at' => NULL,'updated_at' => NULL),
  array('id' => '20','bills_sale_day' => '2021-05-30 17:40:39','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '21','created_at' => NULL,'updated_at' => NULL),
  array('id' => '21','bills_sale_day' => '2021-05-30 17:41:15','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '22','created_at' => NULL,'updated_at' => NULL),
  array('id' => '22','bills_sale_day' => '2021-05-30 17:41:44','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '23','created_at' => NULL,'updated_at' => NULL),
  array('id' => '23','bills_sale_day' => '2021-05-30 17:41:58','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '24','created_at' => NULL,'updated_at' => NULL),
  array('id' => '24','bills_sale_day' => '2021-05-30 17:42:16','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '25','created_at' => NULL,'updated_at' => NULL),
  array('id' => '25','bills_sale_day' => '2021-05-30 17:42:36','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '26','created_at' => NULL,'updated_at' => NULL),
  array('id' => '26','bills_sale_day' => '2021-05-30 17:43:24','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '27','created_at' => NULL,'updated_at' => NULL),
  array('id' => '27','bills_sale_day' => '2021-05-30 17:43:42','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '1050000','bill_custormer_id' => '28','created_at' => NULL,'updated_at' => NULL),
  array('id' => '28','bills_sale_day' => '2021-05-30 17:45:21','bill_pay_day' => NULL,'bill_descriptions' => 'Không','bill_state' => 'Chưa xác thực','staff_set_bill_accepted' => NULL,'staff_set_bill_ship' => NULL,'staff_set_bill_shipping' => NULL,'staff_set_bill_done' => NULL,'staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '105000','bill_custormer_id' => '29','created_at' => NULL,'updated_at' => NULL),
  array('id' => '29','bills_sale_day' => '2021-06-06 22:38:32','bill_pay_day' => '2021-06-08 16:43:40','bill_descriptions' => 'Giao hàng cho trận bóng ngày mai','bill_state' => 'Hủy','staff_set_bill_accepted' => '1','staff_set_bill_ship' => '1','staff_set_bill_shipping' => '1','staff_set_bill_done' => '1','staff_set_bill_cancel' => '1','bill_staff_id' => NULL,'bill_total' => '258000','bill_custormer_id' => '30','created_at' => NULL,'updated_at' => '2021-06-08 11:18:09'),
  array('id' => '30','bills_sale_day' => '2021-06-10 14:50:17','bill_pay_day' => '2021-06-10 14:52:10','bill_descriptions' => 'Không','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '1','staff_set_bill_ship' => '1','staff_set_bill_shipping' => '1','staff_set_bill_done' => '1','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '210000','bill_custormer_id' => '31','created_at' => NULL,'updated_at' => '2021-06-10 07:52:53'),
  array('id' => '31','bills_sale_day' => '2021-06-10 14:51:29','bill_pay_day' => '2021-06-10 14:52:16','bill_descriptions' => 'Không','bill_state' => 'Hoàn thành','staff_set_bill_accepted' => '1','staff_set_bill_ship' => '1','staff_set_bill_shipping' => '1','staff_set_bill_done' => '1','staff_set_bill_cancel' => NULL,'bill_staff_id' => NULL,'bill_total' => '210000','bill_custormer_id' => '32','created_at' => NULL,'updated_at' => '2021-06-10 07:54:19')
);

/* `hat882020`.`bill_details` */
$bill_details = array(
  array('id' => '1','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '2','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '3','product_id' => '13','product_quantity' => '1','product_total' => '35000','bill_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '4','product_id' => '14','product_quantity' => '4','product_total' => '140000','bill_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '5','product_id' => '16','product_quantity' => '1','product_total' => '35000','bill_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '6','product_id' => '17','product_quantity' => '1','product_total' => '35000','bill_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '7','product_id' => '15','product_quantity' => '1','product_total' => '35000','bill_id' => '1','created_at' => NULL,'updated_at' => NULL),
  array('id' => '8','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '2','created_at' => NULL,'updated_at' => NULL),
  array('id' => '9','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '2','created_at' => NULL,'updated_at' => NULL),
  array('id' => '10','product_id' => '13','product_quantity' => '1','product_total' => '35000','bill_id' => '2','created_at' => NULL,'updated_at' => NULL),
  array('id' => '11','product_id' => '14','product_quantity' => '4','product_total' => '140000','bill_id' => '2','created_at' => NULL,'updated_at' => NULL),
  array('id' => '12','product_id' => '16','product_quantity' => '1','product_total' => '35000','bill_id' => '2','created_at' => NULL,'updated_at' => NULL),
  array('id' => '13','product_id' => '17','product_quantity' => '1','product_total' => '35000','bill_id' => '2','created_at' => NULL,'updated_at' => NULL),
  array('id' => '14','product_id' => '15','product_quantity' => '1','product_total' => '35000','bill_id' => '2','created_at' => NULL,'updated_at' => NULL),
  array('id' => '15','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '16','product_id' => '13','product_quantity' => '1','product_total' => '35000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '17','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '18','product_id' => '14','product_quantity' => '1','product_total' => '35000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '19','product_id' => '5','product_quantity' => '1','product_total' => '35000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '20','product_id' => '6','product_quantity' => '1','product_total' => '35000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '21','product_id' => '21','product_quantity' => '1','product_total' => '25000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '22','product_id' => '19','product_quantity' => '1','product_total' => '25000','bill_id' => '3','created_at' => NULL,'updated_at' => NULL),
  array('id' => '23','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '4','created_at' => NULL,'updated_at' => NULL),
  array('id' => '24','product_id' => '14','product_quantity' => '1','product_total' => '35000','bill_id' => '4','created_at' => NULL,'updated_at' => NULL),
  array('id' => '25','product_id' => '16','product_quantity' => '1','product_total' => '35000','bill_id' => '5','created_at' => NULL,'updated_at' => NULL),
  array('id' => '26','product_id' => '18','product_quantity' => '1','product_total' => '35000','bill_id' => '5','created_at' => NULL,'updated_at' => NULL),
  array('id' => '27','product_id' => '11','product_quantity' => '4','product_total' => '140000','bill_id' => '6','created_at' => NULL,'updated_at' => NULL),
  array('id' => '28','product_id' => '5','product_quantity' => '4','product_total' => '140000','bill_id' => '6','created_at' => NULL,'updated_at' => NULL),
  array('id' => '29','product_id' => '6','product_quantity' => '3','product_total' => '105000','bill_id' => '6','created_at' => NULL,'updated_at' => NULL),
  array('id' => '30','product_id' => '11','product_quantity' => '3','product_total' => '105000','bill_id' => '7','created_at' => NULL,'updated_at' => NULL),
  array('id' => '31','product_id' => '14','product_quantity' => '3','product_total' => '105000','bill_id' => '7','created_at' => NULL,'updated_at' => NULL),
  array('id' => '32','product_id' => '12','product_quantity' => '3','product_total' => '105000','bill_id' => '7','created_at' => NULL,'updated_at' => NULL),
  array('id' => '33','product_id' => '11','product_quantity' => '3','product_total' => '105000','bill_id' => '8','created_at' => NULL,'updated_at' => NULL),
  array('id' => '34','product_id' => '14','product_quantity' => '3','product_total' => '105000','bill_id' => '8','created_at' => NULL,'updated_at' => NULL),
  array('id' => '35','product_id' => '12','product_quantity' => '3','product_total' => '105000','bill_id' => '8','created_at' => NULL,'updated_at' => NULL),
  array('id' => '36','product_id' => '18','product_quantity' => '1','product_total' => '35000','bill_id' => '9','created_at' => NULL,'updated_at' => NULL),
  array('id' => '37','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '10','created_at' => NULL,'updated_at' => NULL),
  array('id' => '38','product_id' => '13','product_quantity' => '1','product_total' => '35000','bill_id' => '10','created_at' => NULL,'updated_at' => NULL),
  array('id' => '39','product_id' => '15','product_quantity' => '1','product_total' => '35000','bill_id' => '10','created_at' => NULL,'updated_at' => NULL),
  array('id' => '40','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '11','created_at' => NULL,'updated_at' => NULL),
  array('id' => '41','product_id' => '13','product_quantity' => '1','product_total' => '35000','bill_id' => '11','created_at' => NULL,'updated_at' => NULL),
  array('id' => '42','product_id' => '18','product_quantity' => '1','product_total' => '35000','bill_id' => '11','created_at' => NULL,'updated_at' => NULL),
  array('id' => '43','product_id' => '23','product_quantity' => '1','product_total' => '25000','bill_id' => '11','created_at' => NULL,'updated_at' => NULL),
  array('id' => '44','product_id' => '21','product_quantity' => '1','product_total' => '25000','bill_id' => '11','created_at' => NULL,'updated_at' => NULL),
  array('id' => '45','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '12','created_at' => NULL,'updated_at' => NULL),
  array('id' => '46','product_id' => '14','product_quantity' => '1','product_total' => '35000','bill_id' => '12','created_at' => NULL,'updated_at' => NULL),
  array('id' => '47','product_id' => '13','product_quantity' => '2','product_total' => '70000','bill_id' => '13','created_at' => NULL,'updated_at' => NULL),
  array('id' => '48','product_id' => '15','product_quantity' => '3','product_total' => '105000','bill_id' => '13','created_at' => NULL,'updated_at' => NULL),
  array('id' => '49','product_id' => '18','product_quantity' => '3','product_total' => '105000','bill_id' => '13','created_at' => NULL,'updated_at' => NULL),
  array('id' => '50','product_id' => '16','product_quantity' => '3','product_total' => '105000','bill_id' => '13','created_at' => NULL,'updated_at' => NULL),
  array('id' => '51','product_id' => '17','product_quantity' => '3','product_total' => '105000','bill_id' => '13','created_at' => NULL,'updated_at' => NULL),
  array('id' => '52','product_id' => '5','product_quantity' => '3','product_total' => '105000','bill_id' => '13','created_at' => NULL,'updated_at' => NULL),
  array('id' => '53','product_id' => '7','product_quantity' => '3','product_total' => '87000','bill_id' => '13','created_at' => NULL,'updated_at' => NULL),
  array('id' => '54','product_id' => '18','product_quantity' => '1','product_total' => '35000','bill_id' => '14','created_at' => NULL,'updated_at' => NULL),
  array('id' => '55','product_id' => '17','product_quantity' => '1','product_total' => '35000','bill_id' => '14','created_at' => NULL,'updated_at' => NULL),
  array('id' => '56','product_id' => '16','product_quantity' => '1','product_total' => '35000','bill_id' => '14','created_at' => NULL,'updated_at' => NULL),
  array('id' => '57','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '15','created_at' => NULL,'updated_at' => NULL),
  array('id' => '58','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '15','created_at' => NULL,'updated_at' => NULL),
  array('id' => '59','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '15','created_at' => NULL,'updated_at' => NULL),
  array('id' => '60','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '16','created_at' => NULL,'updated_at' => NULL),
  array('id' => '61','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '16','created_at' => NULL,'updated_at' => NULL),
  array('id' => '62','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '16','created_at' => NULL,'updated_at' => NULL),
  array('id' => '63','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '17','created_at' => NULL,'updated_at' => NULL),
  array('id' => '64','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '17','created_at' => NULL,'updated_at' => NULL),
  array('id' => '65','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '17','created_at' => NULL,'updated_at' => NULL),
  array('id' => '66','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '18','created_at' => NULL,'updated_at' => NULL),
  array('id' => '67','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '18','created_at' => NULL,'updated_at' => NULL),
  array('id' => '68','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '18','created_at' => NULL,'updated_at' => NULL),
  array('id' => '69','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '19','created_at' => NULL,'updated_at' => NULL),
  array('id' => '70','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '19','created_at' => NULL,'updated_at' => NULL),
  array('id' => '71','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '19','created_at' => NULL,'updated_at' => NULL),
  array('id' => '72','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '20','created_at' => NULL,'updated_at' => NULL),
  array('id' => '73','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '20','created_at' => NULL,'updated_at' => NULL),
  array('id' => '74','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '20','created_at' => NULL,'updated_at' => NULL),
  array('id' => '75','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '21','created_at' => NULL,'updated_at' => NULL),
  array('id' => '76','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '21','created_at' => NULL,'updated_at' => NULL),
  array('id' => '77','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '21','created_at' => NULL,'updated_at' => NULL),
  array('id' => '78','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '22','created_at' => NULL,'updated_at' => NULL),
  array('id' => '79','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '22','created_at' => NULL,'updated_at' => NULL),
  array('id' => '80','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '22','created_at' => NULL,'updated_at' => NULL),
  array('id' => '81','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '23','created_at' => NULL,'updated_at' => NULL),
  array('id' => '82','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '23','created_at' => NULL,'updated_at' => NULL),
  array('id' => '83','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '23','created_at' => NULL,'updated_at' => NULL),
  array('id' => '84','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '24','created_at' => NULL,'updated_at' => NULL),
  array('id' => '85','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '24','created_at' => NULL,'updated_at' => NULL),
  array('id' => '86','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '24','created_at' => NULL,'updated_at' => NULL),
  array('id' => '87','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '25','created_at' => NULL,'updated_at' => NULL),
  array('id' => '88','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '25','created_at' => NULL,'updated_at' => NULL),
  array('id' => '89','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '25','created_at' => NULL,'updated_at' => NULL),
  array('id' => '90','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '26','created_at' => NULL,'updated_at' => NULL),
  array('id' => '91','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '26','created_at' => NULL,'updated_at' => NULL),
  array('id' => '92','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '26','created_at' => NULL,'updated_at' => NULL),
  array('id' => '93','product_id' => '17','product_quantity' => '10','product_total' => '350000','bill_id' => '27','created_at' => NULL,'updated_at' => NULL),
  array('id' => '94','product_id' => '16','product_quantity' => '10','product_total' => '350000','bill_id' => '27','created_at' => NULL,'updated_at' => NULL),
  array('id' => '95','product_id' => '14','product_quantity' => '10','product_total' => '350000','bill_id' => '27','created_at' => NULL,'updated_at' => NULL),
  array('id' => '96','product_id' => '15','product_quantity' => '1','product_total' => '35000','bill_id' => '28','created_at' => NULL,'updated_at' => NULL),
  array('id' => '97','product_id' => '17','product_quantity' => '1','product_total' => '35000','bill_id' => '28','created_at' => NULL,'updated_at' => NULL),
  array('id' => '98','product_id' => '16','product_quantity' => '1','product_total' => '35000','bill_id' => '28','created_at' => NULL,'updated_at' => NULL),
  array('id' => '99','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '29','created_at' => NULL,'updated_at' => NULL),
  array('id' => '100','product_id' => '18','product_quantity' => '1','product_total' => '35000','bill_id' => '29','created_at' => NULL,'updated_at' => NULL),
  array('id' => '101','product_id' => '32','product_quantity' => '2','product_total' => '98000','bill_id' => '29','created_at' => NULL,'updated_at' => NULL),
  array('id' => '102','product_id' => '31','product_quantity' => '2','product_total' => '90000','bill_id' => '29','created_at' => NULL,'updated_at' => NULL),
  array('id' => '103','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '30','created_at' => NULL,'updated_at' => NULL),
  array('id' => '104','product_id' => '16','product_quantity' => '3','product_total' => '105000','bill_id' => '30','created_at' => NULL,'updated_at' => NULL),
  array('id' => '105','product_id' => '14','product_quantity' => '1','product_total' => '35000','bill_id' => '30','created_at' => NULL,'updated_at' => NULL),
  array('id' => '106','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '30','created_at' => NULL,'updated_at' => NULL),
  array('id' => '107','product_id' => '11','product_quantity' => '1','product_total' => '35000','bill_id' => '31','created_at' => NULL,'updated_at' => NULL),
  array('id' => '108','product_id' => '16','product_quantity' => '3','product_total' => '105000','bill_id' => '31','created_at' => NULL,'updated_at' => NULL),
  array('id' => '109','product_id' => '14','product_quantity' => '1','product_total' => '35000','bill_id' => '31','created_at' => NULL,'updated_at' => NULL),
  array('id' => '110','product_id' => '12','product_quantity' => '1','product_total' => '35000','bill_id' => '31','created_at' => NULL,'updated_at' => NULL)
);

/* `hat882020`.`categories` */
$categories = array(
  array('id' => '1','categories_name' => 'Cà Phê','categories_slug' => 'ca-phe','categories_parent_node' => '0','categories_images' => 'uploads/image/banners/ca-phe-truyen-thong.jpg','categories_description' => 'Sự kết hợp hoàn hảo giữa hạt cà phê Robusta & Arabica thượng hạng được trồng trên những vùng cao nguyên Việt Nam màu mỡ, qua những bí quyết rang xay độc đáo, Highlands Coffee chúng tôi tự hào giới thiệu những dòng sản phẩm Cà phê mang hương vị đậm đà và tinh tế.','categories_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '2','categories_name' => 'Đồ Đá Xay','categories_slug' => 'do-da-xay','categories_parent_node' => '0','categories_images' => 'uploads/image/banners/do-da-xay.jpg','categories_description' => 'Sảng khoái với thức uống đá xay phong cách Việt. Freeze là thức uống đá xay mát lạnh được pha chế từ những nguyên liệu thuần túy của Việt Nam.
                    KHÁM PHÁ THÊM','categories_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '3','categories_name' => 'Bánh Ngọt','categories_slug' => 'banh-ngot','categories_parent_node' => '0','categories_images' => 'uploads/image/banners/banh-ngot.jfif','categories_description' => 'Còn gì tuyệt vời hơn khi kết hợp thưởng thức đồ uống của bạn cùng với những chiếc bánh ngọt ngon tinh tế được làm thủ công ngay tại bếp bánh của Highlands Coffee. Những chiếc bánh của chúng tôi mang hương vị đặc trưng của ẩm thực Việt và còn là sự Tận Tâm, gửi gắm mà chúng tôi dành cho Quý khách hàng.','categories_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '4','categories_name' => 'Đồ Ăn Chơi','categories_slug' => 'do-an-choi','categories_parent_node' => '0','categories_images' => 'uploads/image/banners/do-an-choi.jfif','categories_description' => 'Không chỉ có không gian thoáng mái, yên tĩnh để nhâm nhi café mà còn phục vụ những món ăn ngon miệng cho khách hàng đang trở thành điểm đến yêu thích của rất nhiều người','categories_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '5','categories_name' => 'Trà Hoa Quả','categories_slug' => 'tra-hoa-qua','categories_parent_node' => '0','categories_images' => 'uploads/image/banners/tra-hoa-qua.jpg','categories_description' => 'Hương vị tự nhiên, thơm ngon của Trà Việt với phong cách hiện đại tại Highlands Coffee sẽ giúp bạn gợi mở vị giác của bản thân và tận hưởng một cảm giác thật khoan khoái, tươi mới.','categories_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '6','categories_name' => 'Cà Phê Đổi Mới','categories_slug' => 'ca-phe-doi-moi','categories_parent_node' => '1','categories_images' => 'uploads/image/banners/ca-phe-doi-moi.jpg','categories_description' => 'Việt Nam tự hào sở hữu một di sản văn hóa cà phê giàu có, và Phin chính là linh hồn, là nét văn hóa thưởng thức cà phê đã ăn sâu vào tiềm thức biết bao người Việt. Cà phê rang xay được chiết xuất chậm rãi từng giọt một thông qua dụng cụ lọc bằng kim loại có tên là Phin, cũng giống như thể hiện sự sâu sắc trong từng suy nghĩ và chân thành trong những mối quan hệ hiện hữu. Bạn có thể tùy thích lựa chọn uống nóng hoặc dùng chung với đá, có hoặc không có sữa đặc. Highlands Coffee tự hào phục vụ cà phê Việt theo cách truyền thống của người Việt.','categories_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '7','categories_name' => 'Cà Phê Nguyên Chất','categories_slug' => 'ca-phe-nguyen-chat','categories_parent_node' => '1','categories_images' => 'uploads/image/banners/ca-phe-truyen-thong.jpg','categories_description' => 'Một thế hệ Cà Phê Phin Việt Nam hoàn toàn mới, phục vụ cho thế hệ trẻ đầy nhiệt huyết, độc lập và sáng tạo. Vẫn mang trong mình tinh tuý chắt lọc từ Cà Phê Phin Việt Nam nhưng êm chất Phin, kết hợp độc đáo cùng những vị ngon từ Kem Sữa - Hạnh Nhân - Choco. PhinDi, Cà Phê Phin Thế Hệ Mới - Chất Phin Êm, Ngon Tròn Vị!','categories_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '8','categories_name' => 'Cà Phê Cho Bóng Đá','categories_slug' => 'ca-phe-cho-bong-da','categories_parent_node' => '7','categories_images' => 'uploads/image/categories/ca-phe-cho-bong-da.jpg','categories_description' => 'ádsad','categories_is_disable' => '0','created_at' => NULL,'updated_at' => NULL)
);

/* `hat882020`.`customers` */
$customers = array(
  array('id' => '1','customer_name' => 'Nguyễn Đức Tuấn Anh','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-17 17:11:25','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '2','customer_name' => 'NguyễnTuấn Anh 12','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-17 17:12:00','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '3','customer_name' => 'Nguyễn Thị Nghĩa','customer_phone_number' => '0981231123','customer_date_buy' => '2021-05-17 18:20:07','customer_email' => 'nghianguyen@gmail.com','customer_address' => 'An Vĩ Khoái Châu Hưng Yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '4','customer_name' => 'Hà Thị Hồ','customer_phone_number' => '0981231123','customer_date_buy' => '2021-05-17 18:27:38','customer_email' => 'haho@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '5','customer_name' => 'Anh thị Lung','customer_phone_number' => '0321884321','customer_date_buy' => '2021-05-17 18:28:20','customer_email' => 'lung@gmail.com','customer_address' => 'Amercinoa ad','created_at' => NULL,'updated_at' => NULL),
  array('id' => '6','customer_name' => 'Anh thị Lung','customer_phone_number' => '0321884321','customer_date_buy' => '2021-05-17 20:38:18','customer_email' => 'lung@gmail.com','customer_address' => 'Mỹ Hào - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '7','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-23 14:43:57','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Mỹ Hào - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '8','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-23 14:45:10','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Mỹ Hào - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '9','customer_name' => 'Hiếu','customer_phone_number' => '0912354320','customer_date_buy' => '2021-05-23 14:49:04','customer_email' => 'hieungo@gmail.com','customer_address' => 'Mỹ Hào - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '10','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-24 15:44:35','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'An Vĩ Khoái Châu Hưng Yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '11','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-27 16:15:14','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '12','customer_name' => 'Hiếu','customer_phone_number' => '0912354320','customer_date_buy' => '2021-05-27 17:15:23','customer_email' => 'hieungo@gmail.com','customer_address' => 'Dân Tiến - Dị Sử','created_at' => NULL,'updated_at' => NULL),
  array('id' => '13','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 12:10:38','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Mỹ Hào - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '14','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 16:43:08','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '15','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 16:44:19','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '16','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 17:38:07','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '17','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 17:38:43','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '18','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 17:38:47','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '19','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 17:38:51','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '20','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 17:40:01','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '21','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 17:40:39','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '22','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 17:41:15','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '23','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 17:41:44','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '24','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 17:41:58','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '25','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 17:42:16','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '26','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 17:42:36','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '27','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 17:43:24','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '28','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 17:43:42','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '29','customer_name' => 'Tuan Anh Nguyen Duc','customer_phone_number' => '+84986703811','customer_date_buy' => '2021-05-30 17:45:21','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '30','customer_name' => 'Tuan Anh','customer_phone_number' => '0986703811','customer_date_buy' => '2021-06-06 22:38:32','customer_email' => 'tuananh010320@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '31','customer_name' => 'TuanAnh Nguyen','customer_phone_number' => '0986703811','customer_date_buy' => '2021-06-10 14:50:17','customer_email' => 'tuananhnguyen3883@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL),
  array('id' => '32','customer_name' => 'TuanAnh Nguyen','customer_phone_number' => '0986703811','customer_date_buy' => '2021-06-10 14:51:29','customer_email' => 'tuananhnguyen3883@gmail.com','customer_address' => 'Dân Tiến - Khoái Châu - Hưng yên','created_at' => NULL,'updated_at' => NULL)
);

/* `hat882020`.`failed_jobs` */
$failed_jobs = array(
);

/* `hat882020`.`migrations` */
$migrations = array(
  array('id' => '483','migration' => '2014_10_12_000000_create_users_table','batch' => '1'),
  array('id' => '484','migration' => '2014_10_12_100000_create_password_resets_table','batch' => '1'),
  array('id' => '485','migration' => '2019_08_19_000000_create_failed_jobs_table','batch' => '1'),
  array('id' => '486','migration' => '2021_04_16_152822_create_categories_table','batch' => '1'),
  array('id' => '487','migration' => '2021_04_17_163057_create_products_table','batch' => '1'),
  array('id' => '488','migration' => '2021_04_21_114545_create_sale_prices_table','batch' => '1'),
  array('id' => '489','migration' => '2021_04_21_114617_create_sale_offs_table','batch' => '1'),
  array('id' => '490','migration' => '2021_04_23_012239_create_staff_types_table','batch' => '1'),
  array('id' => '491','migration' => '2021_04_23_012434_create_staff_table','batch' => '1'),
  array('id' => '492','migration' => '2021_05_15_101041_create_customers_table','batch' => '1'),
  array('id' => '493','migration' => '2021_05_15_101118_create_bills_table','batch' => '1'),
  array('id' => '494','migration' => '2021_05_15_101129_create_bill_details_table','batch' => '1')
);

/* `hat882020`.`password_resets` */
$password_resets = array(
);

/* `hat882020`.`products` */
$products = array(
  array('id' => '2','categories_id' => '7','product_name' => 'Cà Phê Đen Đá','product_slug' => 'ca-phe-den-da','product_description' => 'Dành cho những tín đồ cà phê đích thực! Hương vị cà phê truyền thống được phối trộn độc đáo tại Highlands. Cà phê đậm đà pha hoàn toàn từ Phin, cho thêm 1 thìa đường, một ít đá viên mát lạnh, tạo nên Phin Đen Đá mang vị cà phê đậm đà chất Phin. ','product_image' => 'uploads/image/products/ca-phe-den-da.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '3','categories_id' => '7','product_name' => 'Cà Phê Đen Nóng','product_slug' => 'ca-phe-den-nong','product_description' => 'Dành cho những tín đồ cà phê đích thực! Hương vị cà phê truyền thống được phối trộn độc đáo tại Highlands. Cà phê đậm đà pha từ Phin, cho thêm 1 thìa đường, mang đến vị cà phê đậm đà chất Phin. ','product_image' => 'uploads/image/products/ca-phe-den-da.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '4','categories_id' => '7','product_name' => 'Cà Phê Sữa Nóng','product_slug' => 'ca-phe-sua-nong','product_description' => 'Hương vị cà phê Việt Nam đích thực! Từng hạt cà phê hảo hạng được chọn bằng tay, phối trộn độc đáo giữa hạt Robusta từ cao nguyên Việt Nam, thêm Arabica thơm lừng. Kết hợp với nước sôi từng giọt cà phê được chiết xuất từ Phin truyền thống, hoà cùng sữa đặc sánh tạo nên ly Phin Sữa Nóng – Đậm đà chất Phin.','product_image' => 'uploads/image/products/ca-phe-sua-da.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '5','categories_id' => '6','product_name' => 'PhiDi Kem Sữa','product_slug' => 'phidi-kem-sua','product_description' => 'PhinDi Kem Sữa - Cà phê Phin thế hệ mới với chất Phin êm hơn, kết hợp cùng Kem Sữa béo ngậy mang đến hương vị mới lạ, không thể hấp dẫn hơn!','product_image' => 'uploads/image/products/phi-di-kem-sua.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '6','categories_id' => '6','product_name' => 'PhiDi Choco','product_slug' => 'phidi-choco','product_description' => 'PhinDi Choco - Cà phê Phin thế hệ mới với chất Phin êm hơn, kết hợp cùng Choco ngọt tan mang đến hương vị mới lạ, không thể hấp dẫn hơn!','product_image' => 'uploads/image/products/phi-di-cho-co.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '7','categories_id' => '6','product_name' => 'Cà Phê Sữa Chua','product_slug' => 'ca-phe-sua-chua','product_description' => 'Nhâm nhi một tách cà phê mỗi ngày là cách tiếp thêm năng lượng tích cực của nhiều thế hệ người Việt Nam. Để hương vị cà phê truyền thống không nhàm chán, bạn có thể học cách pha cafe sữa chua của chúng tôi. Đây là sự kết hợp hoàn hảo, mang đến hương vị thanh mát mới lạ, lại có lợi cho sức khỏe, hệ tiêu hóa của bạn đấy! ','product_image' => 'uploads/image/products/bac-xiu.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '8','categories_id' => '6','product_name' => 'Cà Phê Trứng','product_slug' => 'ca-phe-trung','product_description' => 'Nếu là người Hà thành hay là những người sành và yêu thích cafe thì chắc hẳn bạn không còn xa lạ gì với món cafe trứng nữa rồi. Được chế biến và khởi nguồn đầu tiên từ Hà Nội, đến nay cafe trứng dường như còn nổi danh trên khắp thế giới thu hút rất nhiều du khách đến thưởng thức.','product_image' => 'uploads/image/products/ca-phe-sua-da.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '9','categories_id' => '6','product_name' => 'Bạc Xỉu','product_slug' => 'bac-xiu','product_description' => 'Nếu Phin Sữa Đá dành cho các bạn đam mê vị đậm đà, thì Bạc Xỉu Đá là một sự lựa chọn nhẹ “đô" cà phê nhưng vẫn thơm ngon, chất lừ không kém!','product_image' => 'uploads/image/products/bac-xiu.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '10','categories_id' => '6','product_name' => 'Cà Phê Cốt Dừa','product_slug' => 'ca-phe-cot-dua','product_description' => 'Bạn có phải là fan của món cafe cốt dừa vô cùng nổi tiếng của Cộng cà phê? Với những ai yêu cà phê và thích thú với hương vị béo ngậy của dừa hòa quyện với vị đắng đậm đà của cà phê thì không thể bỏ qua món đồ uống này.','product_image' => 'uploads/image/products/ca-phe-cot-dua.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '11','categories_id' => '2','product_name' => 'Freeze Trà Xanh','product_slug' => 'freeze-tra-xanh','product_description' => 'Thức uống rất được ưa chuộng! Trà xanh thượng hạng từ cao nguyên Việt Nam, kết hợp cùng đá xay, thạch trà dai dai, thơm ngon và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Trà Xanh thơm ngon, mát lạnh, chinh phục bất cứ ai!','product_image' => 'uploads/image/products/freeze-tra-xanh.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '12','categories_id' => '2','product_name' => 'Freeze Socola','product_slug' => 'freeze-socola','product_description' => 'Thiên đường đá xay sô cô la! Từ những thanh sô cô la Việt Nam chất lượng được đem xay với đá cho đến khi mềm mịn, sau đó thêm vào thạch sô cô la dai giòn, ở trên được phủ một lớp kem whip beo béo và sốt sô cô la ngọt ngào. Tạo thành Freeze Sô-cô-la ngon mê mẩn chinh phục bất kì ai!','product_image' => 'uploads/image/products/freeze-socola.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '13','categories_id' => '2','product_name' => 'Freeze Việt Quất','product_slug' => 'freeze-viet-quat','product_description' => 'Thức uống rất được ưa chuộng! Việt quất thượng hạngkết hợp cùng đá xay, sốt Việt Quất, thơm ngon và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Việt Quất thơm ngon, mát lạnh, chinh phục bất cứ ai!','product_image' => 'uploads/image/products/freeze-viet-quat.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '14','categories_id' => '2','product_name' => 'Freeze KiWi','product_slug' => 'freeze-kiwi','product_description' => 'Thức uống rất được ưa chuộng! Kiwi thượng hạng kết hợp cùng đá xay, sốt Kiwi, thơm ngon và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Kiwi thơm ngon, mát lạnh, chinh phục bất cứ ai!','product_image' => 'uploads/image/products/freeze-tra-xanh.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '15','categories_id' => '2','product_name' => 'Caramel Phin Freeze','product_slug' => 'caramel-phin-freeze','product_description' => 'Thơm ngon khó cưỡng! Được kết hợp từ cà phê truyền thống chỉ có tại Highlands Coffee, cùng với caramel, thạch cà phê và đá xay mát lạnh. Trên cùng là lớp kem tươi thơm béo và caramel ngọt ngào. Món nước phù hợp trong những cuộc gặp gỡ bạn bè, bởi sự ngọt ngào thường mang mọi người xích lại gần nhau.','product_image' => 'uploads/image/products/caramel-freeze.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '16','categories_id' => '2','product_name' => 'Freeze Cacao','product_slug' => 'freeze-cacao','product_description' => 'Thơm ngon đậm đà! Được kết hợp từ cà phê pha Phin truyền thống chỉ có tại Highlands Coffee, cùng với thạch cà phê và đá xay mát lạnh. Trên cùng là lớp kem tươi thơm béo và bột ca cao đậm đà. Món nước hoàn hảo để khởi đầu câu chuyện cùng bạn bè.','product_image' => 'uploads/image/products/freeze-cacao.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '17','categories_id' => '2','product_name' => 'Freeze Trà Đào','product_slug' => 'freeze-tra-dao','product_description' => 'Thức uống rất được ưa chuộng! Đào thượng hạng kết hợp cùng đá xay, thạch đào dai dai, thơm ngon và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Trà Đào thơm ngon, mát lạnh, chinh phục bất cứ ai!','product_image' => 'uploads/image/products/freeze-tra-dao.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '18','categories_id' => '2','product_name' => 'Freeze Dâu Tây','product_slug' => 'freeze-dau-tay','product_description' => 'Thức uống rất được ưa chuộng! Dâu thượng hạng kết hợp cùng đá xay, mứt dâu dai dai, thơm ngon với sữa chua tuyệt hảo và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Dâu Tây thơm ngon, mát lạnh, chinh phục bất cứ ai!','product_image' => 'uploads/image/products/freeze-dau-tay.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '19','categories_id' => '3','product_name' => 'Bánh Tiramisu','product_slug' => 'banh-tiramisu','product_description' => 'Tiramisu là một loại bánh ngọt tráng miệng vị cà phê của nước Ý, gồm các lớp bánh quy Savoiardi, [savoˈjardi] nhúng cà phê xen kẽ với hỗn hợp trứng, đường, phô mai mascarpone đánh bông, thêm một ít bột cacao. Công thức bánh này được biến tấu thành nhiều món bánh và món tráng miệng khác nhau.','product_image' => 'uploads/image/products/banh-tiramisu.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '20','categories_id' => '3','product_name' => 'Bánh CheeseCake Caramel','product_slug' => 'banh-cheesecake-caramel','product_description' => 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn, cafe và Caramel hảo hạn','product_image' => 'uploads/image/products/chessecake-caramel.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '21','categories_id' => '3','product_name' => 'Bánh CheeseCake Cam','product_slug' => 'banh-cheesecake-cam','product_description' => 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn và Cam hảo hạn','product_image' => 'uploads/image/products/chessecake-cam.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '22','categories_id' => '3','product_name' => 'Bánh CheeseCake Đào','product_slug' => 'banh-cheesecake-dao','product_description' => 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn và Đào hảo hạn','product_image' => 'uploads/image/products/chessecake-dao.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '23','categories_id' => '3','product_name' => 'Bánh CheeseCake Việt Quất','product_slug' => 'banh-cheesecake-viet-quat','product_description' => 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn và Việt Quất hảo hạn','product_image' => 'uploads/image/products/chessecake-viet-quat.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '24','categories_id' => '3','product_name' => 'Bánh CheeseCake Matcha','product_slug' => 'banh-cheesecake-matcha','product_description' => 'Chessecake trà xanh là sự kết hợp hoàn hảo của phô mai, sữa tươi, bánh vụn và Matcha hảo hạn','product_image' => 'uploads/image/products/chessecake-matcha.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '25','categories_id' => '5','product_name' => 'Trà Đào Cam Sả','product_slug' => 'tra-dao-cam-sa','product_description' => 'Vị thanh ngọt của đào Hy Lạp, vị chua dịu của Cam Vàng nguyên vỏ, vị chát của trà đen tươi được ủ mới mỗi 4 tiếng, cùng hương thơm nồng đặc trưng của sả chính là điểm sáng làm nên sức hấp dẫn của thức uống này. Sản phẩm hiện có 2 phiên bản Nóng và Lạnh phù hợp cho mọi thời gian trong năm.','product_image' => 'uploads/image/products/tra-thanh-dao.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '26','categories_id' => '5','product_name' => 'Trà Thanh Đào','product_slug' => 'tra-thanh-dao','product_description' => 'Một trải nghiệm thú vị khác! Sự hài hòa giữa vị trà cao cấp, vị sả thanh mát và những miếng đào thơm ngon mọng nước sẽ mang đến cho bạn một thức uống tuyệt vời.','product_image' => 'uploads/image/products/tra-thanh-dao.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '27','categories_id' => '5','product_name' => 'Trà Thạch Đào','product_slug' => 'tra-thach-dao','product_description' => 'Vị trà đậm đà kết hợp cùng những miếng đào thơm ngon mọng nước cùng thạch đào giòn dai. Thêm vào ít sữa để gia tăng vị béo.','product_image' => 'uploads/image/products/tra-thach-dao.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '28','categories_id' => '5','product_name' => 'Trà Sen Vàng','product_slug' => 'tra-sen-vang','product_description' => 'Thức uống chinh phục những thực khách khó tính! Sự kết hợp độc đáo giữa trà Ô long, hạt sen thơm bùi và củ năng giòn tan. Thêm vào chút sữa sẽ để vị thêm ngọt ngào.','product_image' => 'uploads/image/products/tra-sen-vang.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '29','categories_id' => '5','product_name' => 'Trà Thạch Vải','product_slug' => 'tra-thach-vai','product_description' => 'Một sự kết hợp thú vị giữa trà đen, những quả vải thơm ngon và thạch giòn khó cưỡng, mang đến thức uống tuyệt hảo!','product_image' => 'uploads/image/products/tra-thach-vai.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '30','categories_id' => '5','product_name' => 'Trà Đào Dầm','product_slug' => 'tra-dao-dam','product_description' => 'Một sự kết hợp thú vị giữa trà đen, sốt đào thơm ngon và đào miếng khó cưỡng, mang đến thức uống tuyệt hảo!','product_image' => 'uploads/image/products/tra-dao-dam.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '31','categories_id' => '4','product_name' => 'Pizza Bò Ngô','product_slug' => 'pizza-bo-ngo','product_description' => 'Vị chua chua, ngọt ngọt của dứa kết hợp với vỏ bánh giòn xốp cùng với thịt bò băm có thể tạo nên hương vị pizza đặc trưng khiến bạn nhớ mãi chẳng quên. Cũng bởi vậy mà pizza bò băm luôn là "best-seller" trong menu của các tiệm bánh pizza nổi tiếng.','product_image' => 'uploads/image/products/pizza-bo-ngo.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '32','categories_id' => '4','product_name' => 'Pizza Hải Sản','product_slug' => 'pizza-hai-san','product_description' => 'Vị dai giòn sần sật của mực xen lẫn vị ngọt của tôm sú quyện hương phô mai cùng rau củ thơm ngon, dễ ăn và dễ đi vào lòng người ở mọi lứa tuổi nhất cực yêu thích.','product_image' => 'uploads/image/products/pizza-hai-san.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '33','categories_id' => '4','product_name' => 'Hướng Dương Nguyên Vị','product_slug' => 'huong-duong-nguyen-vi','product_description' => '','product_image' => 'uploads/image/products/huong-duong-thuong.jfif','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '34','categories_id' => '4','product_name' => 'Hướng Dương Vị Dừa','product_slug' => 'huong-duong-vi-dua','product_description' => '','product_image' => 'uploads/image/products/huong-duong-dua.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '30','product_amout_sales' => '30','product_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-05-17 10:10:53'),
  array('id' => '35','categories_id' => '1','product_name' => 'RƯỢU TEQUILA 1800 COCONUT12312','product_slug' => 'ruou-tequila-1800-coconut','product_description' => 'Không','product_image' => 'uploads/image/products/ruou-tequila-1800-coconut12312.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '23','product_amout_sales' => '0','product_is_disable' => '1','created_at' => NULL,'updated_at' => '2021-06-10 11:10:57'),
  array('id' => '36','categories_id' => '1','product_name' => 'RƯỢU TEQUILA 1800 COCONUT','product_slug' => 'ruou-tequila-1800-coconut','product_description' => 'ádsad','product_image' => 'uploads/image/products/ruou-tequila-1800-coconut.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '29','product_amout_sales' => '0','product_is_disable' => '1','created_at' => NULL,'updated_at' => '2021-06-10 11:16:13'),
  array('id' => '37','categories_id' => '1','product_name' => 'RƯỢU TEQUILA 1800 COCONUT','product_slug' => 'ruou-tequila-1800-coconut','product_description' => 'Không','product_image' => 'uploads/image/products/ruou-tequila-1800-coconut.jpg','product_unit' => 'Cốc','product_size' => '0','product_amout_imports' => '23','product_amout_sales' => '0','product_is_disable' => '0','created_at' => NULL,'updated_at' => NULL)
);

/* `hat882020`.`sale_offs` */
$sale_offs = array(
);

/* `hat882020`.`sale_prices` */
$sale_prices = array(
  array('id' => '1','product_id' => '1','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '19000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '2','product_id' => '2','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '19000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '3','product_id' => '3','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '19000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '4','product_id' => '4','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '19000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '5','product_id' => '5','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '35000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '6','product_id' => '6','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '35000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '7','product_id' => '7','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '29000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '8','product_id' => '8','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '35000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '9','product_id' => '9','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '29000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '10','product_id' => '10','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '35000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '11','product_id' => '11','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '35000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '12','product_id' => '12','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '35000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '13','product_id' => '13','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '35000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '14','product_id' => '14','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '35000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '15','product_id' => '15','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '35000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '16','product_id' => '16','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '35000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '17','product_id' => '17','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '35000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '18','product_id' => '18','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '35000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '19','product_id' => '19','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '25000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '20','product_id' => '20','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '25000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '21','product_id' => '21','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '25000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '22','product_id' => '22','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '25000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '23','product_id' => '23','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '25000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '24','product_id' => '24','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '25000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '25','product_id' => '25','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '29000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '26','product_id' => '26','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '29000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '27','product_id' => '27','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '29000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '28','product_id' => '28','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '29000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '29','product_id' => '29','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '29000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '30','product_id' => '30','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '29000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '31','product_id' => '31','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '45000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '32','product_id' => '32','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '49000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '33','product_id' => '33','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '10000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '34','product_id' => '34','sale_price_date_import' => '2020-08-08 00:00:00','sale_price_date_start' => '2020-08-08 00:00:00','sale_price_date_end' => NULL,'sale_price_amount' => '20','sale_price_values' => '13000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '35','product_id' => '35','sale_price_date_import' => '2021-06-10 10:34:15','sale_price_date_start' => '2021-06-10 10:34:15','sale_price_date_end' => '2021-06-10 10:51:16','sale_price_amount' => '0','sale_price_values' => '250000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-06-10 10:51:16'),
  array('id' => '36','product_id' => '35','sale_price_date_import' => '2021-06-10 10:51:16','sale_price_date_start' => '2021-06-10 10:51:16','sale_price_date_end' => '2021-06-10 11:09:02','sale_price_amount' => '0','sale_price_values' => '250000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-06-10 11:09:02'),
  array('id' => '37','product_id' => '35','sale_price_date_import' => '2021-06-10 11:09:02','sale_price_date_start' => '2021-06-10 11:09:02','sale_price_date_end' => '2021-06-10 11:09:56','sale_price_amount' => '0','sale_price_values' => '250000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-06-10 11:09:56'),
  array('id' => '38','product_id' => '35','sale_price_date_import' => '2021-06-10 11:09:56','sale_price_date_start' => '2021-06-10 11:09:56','sale_price_date_end' => '2021-06-10 11:10:23','sale_price_amount' => '0','sale_price_values' => '250000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-06-10 11:10:23'),
  array('id' => '39','product_id' => '35','sale_price_date_import' => '2021-06-10 11:10:23','sale_price_date_start' => '2021-06-10 11:10:23','sale_price_date_end' => '2021-06-10 11:10:57','sale_price_amount' => '0','sale_price_values' => '250000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-06-10 11:10:57'),
  array('id' => '40','product_id' => '36','sale_price_date_import' => '2021-06-10 11:10:50','sale_price_date_start' => '2021-06-10 11:10:50','sale_price_date_end' => '2021-06-10 11:11:12','sale_price_amount' => '0','sale_price_values' => '20000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-06-10 11:11:12'),
  array('id' => '41','product_id' => '35','sale_price_date_import' => '2021-06-10 11:10:57','sale_price_date_start' => '2021-06-10 11:10:57','sale_price_date_end' => NULL,'sale_price_amount' => '0','sale_price_values' => '250000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '42','product_id' => '36','sale_price_date_import' => '2021-06-10 11:11:12','sale_price_date_start' => '2021-06-10 11:11:12','sale_price_date_end' => '2021-06-10 11:13:36','sale_price_amount' => '0','sale_price_values' => '20000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-06-10 11:13:36'),
  array('id' => '43','product_id' => '36','sale_price_date_import' => '2021-06-10 11:13:36','sale_price_date_start' => '2021-06-10 11:13:36','sale_price_date_end' => '2021-06-10 11:13:44','sale_price_amount' => '0','sale_price_values' => '20000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => '2021-06-10 11:13:44'),
  array('id' => '44','product_id' => '36','sale_price_date_import' => '2021-06-10 11:13:44','sale_price_date_start' => '2021-06-10 11:13:44','sale_price_date_end' => NULL,'sale_price_amount' => '0','sale_price_values' => '20000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '45','product_id' => '37','sale_price_date_import' => '2021-06-10 11:20:28','sale_price_date_start' => '2021-06-10 11:20:28','sale_price_date_end' => NULL,'sale_price_amount' => '0','sale_price_values' => '19000','sale_price_is_disable' => '0','created_at' => NULL,'updated_at' => NULL)
);

/* `hat882020`.`staff` */
$staff = array(
  array('id' => '1','staff_name' => 'Nguyễn Đức Tuấn Anh','staff_types_id' => '1','staff_image' => 'uploads/image/staffs/nguyen-duc-tuan-anh.jpg','staff_sex' => 'Nam','staff_birthday' => '2000-01-03','staff_date_join' => '2020-08-08','staff_address' => 'An Vĩ Khoái Châu Hưng Yên','staff_account' => 'tuananh0103','staff_password' => '123','staff_role' => 'Quản lý','staff_phone_number' => '0986703811','staff_email' => 'tuananh010320@gmail.com','staff_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '2','staff_name' => 'Nguyễn Tuấn Anh','staff_types_id' => '1','staff_image' => 'uploads/image/staffs/nguyen-tuan-anh.jpg','staff_sex' => 'Nam','staff_birthday' => '2000-01-03','staff_date_join' => '2020-08-08','staff_address' => 'An Vĩ Khoái Châu Hưng Yên','staff_account' => 'tuananh','staff_password' => '123','staff_role' => 'Quản lý','staff_phone_number' => '0986703811','staff_email' => 'tuananh@gmail.com','staff_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '3','staff_name' => 'Nguyễn Thị Thảo','staff_types_id' => '2','staff_image' => 'uploads/image/staffs/nguyen-thi-thao.jpg','staff_sex' => 'Nữ','staff_birthday' => '2000-01-03','staff_date_join' => '2020-08-08','staff_address' => 'An Vĩ Khoái Châu Hưng Yên','staff_account' => 'thao81','staff_password' => '123','staff_role' => 'Nhân viên','staff_phone_number' => '0986703811','staff_email' => 'nguyenthithao@gmail.com','staff_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '4','staff_name' => 'Đỗ Thị Mỹ Linh','staff_types_id' => '4','staff_image' => 'uploads/image/staffs/do-thi-my-linh.jpg','staff_sex' => 'Nữ','staff_birthday' => '2000-01-03','staff_date_join' => '2020-08-08','staff_address' => 'An Vĩ Khoái Châu Hưng Yên','staff_account' => 'linh81','staff_password' => '123','staff_role' => 'Nhân viên','staff_phone_number' => '0986703811','staff_email' => 'dothimylinh@gmail.com','staff_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '5','staff_name' => 'Lệ Ngọc Lệ','staff_types_id' => '3','staff_image' => 'uploads/image/staffs/le-ngoc-le.jpg','staff_sex' => 'Nữ','staff_birthday' => '2000-01-03','staff_date_join' => '2020-08-08','staff_address' => 'An Vĩ Khoái Châu Hưng Yên','staff_account' => 'le81','staff_password' => '123','staff_role' => 'Nhân viên','staff_phone_number' => '0986703811','staff_email' => 'lengocle@gmail.com','staff_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '6','staff_name' => 'Chu Hải Long','staff_types_id' => '4','staff_image' => 'uploads/image/staffs/chu-hai-long.jpg','staff_sex' => 'Nam','staff_birthday' => '2000-01-03','staff_date_join' => '2020-08-08','staff_address' => 'An Vĩ Khoái Châu Hưng Yên','staff_account' => 'long81','staff_password' => '123','staff_role' => 'Nhân viên','staff_phone_number' => '0986703811','staff_email' => 'chuhailong@gmail.com','staff_is_disable' => '0','created_at' => NULL,'updated_at' => NULL)
);

/* `hat882020`.`staff_types` */
$staff_types = array(
  array('id' => '1','staff_types_name' => 'Quản lý','staff_types_desceptions' => 'Người có chức vụ cao trong cửa hàng','staff_types_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '2','staff_types_name' => 'Nhân viên quản lý đơn hàng','staff_types_desceptions' => 'Người có chức vụ nhận các đơn hàng chưa xác thực và xác thực đơn hàng thông qua khách hàng để báo cho bên chế biến','staff_types_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '3','staff_types_name' => 'Nhân viên pha chế','staff_types_desceptions' => 'Người có chức vụ nhận các đơn hàng đã xác thực để làm đồ cho khách, sau khi làm xong sẽ đặt lại tình trạng đơn hàng là cần giao hàng','staff_types_is_disable' => '0','created_at' => NULL,'updated_at' => NULL),
  array('id' => '4','staff_types_name' => 'Nhân viên giao hàng','staff_types_desceptions' => 'Người có chức vụ nhận các đơn hàng có tình trạng cần giao hàng và khi nhận đơn hàng sẽ để trạng thái là đang giao, hoàn thành hoặc hủy','staff_types_is_disable' => '0','created_at' => NULL,'updated_at' => NULL)
);

/* `hat882020`.`users` */
$users = array(
);
